// finance.service.ts

import { Transaction, Budget, Bill, Goal, Debt, ITransaction, IGoal, IBill, IBudget } from './finance.model';
import { Expense } from '../expense/expense.model';
import { Trip } from '../trips/trip.model';
import { Settlement } from '../settlement/settlement.model';
import { User } from '../auth/auth.model';
import mongoose, { Types } from 'mongoose';
import { AppError } from '../../shared/errors/AppError';
import { logger } from '../../config/logger';

// ============================================================
// TYPES
// ============================================================

interface DashboardFilters {
  month?: string;
  includeTripExpenses?: boolean;
}

interface TransactionFilters {
  // Basic filters1
  type?: string;
  category?: string;
  tripId?: string;
  tags?: string[];
  search?: string;
  
  // Date filters (choose one approach)
  day?: string;              // YYYY-MM-DD
  month?: string;            // 1-12 (uses current year)
  year?: number;             // YYYY
  monthAndYear?: {           // OR use both together
    month: string;           // 1-12
    year: number;            // YYYY
  };
  dateRange?: {              // Custom range (highest priority)
    startDate?: string;      // ISO date string
    endDate?: string;        // ISO date string
  };
  
  // Legacy (backward compatibility)
  startDate?: string;
  endDate?: string;
  
  // Pagination & sorting
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

interface AnalyticsFilters {
  period?: 'week' | 'month' | 'quarter' | 'year' | 'all';
  startDate?: string;
  endDate?: string;
}

// ============================================================
// FINANCE SERVICE
// ============================================================

export class FinanceService {

  // ============================================================
  // SYNC: Pull TripSplit expenses into personal finance
  // ============================================================

  static async syncTripExpenses(userId: string): Promise<{ synced: number; skipped: number }> {
    try {
      const expenses = await Expense.find({
        $or: [
          { paidBy: userId },
          { 'splits.userId': userId },
        ],
        isArchived: false,
      }).lean();

      if (expenses.length === 0) {
        await this.syncSettlementTransactions(userId);
        return { synced: 0, skipped: 0 };
      }

      const allExpenseIds = expenses.map((e: any) => e._id);
      const existingTxns = await Transaction.find({
        userId,
        expenseId: { $in: allExpenseIds },
        isAutoGenerated: true,
      }).lean();

      const existingMap = new Map<string, any>();
      existingTxns.forEach((t: any) => {
        existingMap.set(String(t.expenseId), t);
      });

      const tripIds = [...new Set(expenses.map((e: any) => String(e.tripId)).filter(Boolean))];
      const trips = await Trip.find({ _id: { $in: tripIds } }).select('title').lean();
      const tripMap = new Map<string, string>();
      trips.forEach((t: any) => tripMap.set(String(t._id), t.title));

      let synced = 0;
      let skipped = 0;
      const bulkOps: any[] = [];
      const updateOps: Array<() => Promise<void>> = [];

      for (const expense of expenses) {
        const mySplit = expense.splits.find((s: any) => s.userId === userId);
        const paidBack = expense.splits
          .filter((s: any) => s.isPaid && s.userId !== userId)
          .reduce((sum: number, s: any) => sum + s.amountBase, 0);
        const myAmount = expense.paidBy === userId
          ? expense.amountBase - paidBack
          : (mySplit?.amountBase || 0);

        const existing = existingMap.get(String(expense._id));

        if (existing) {
          if (existing.amount !== myAmount || existing.myShare !== (mySplit?.amountBase ?? 0)) {
            updateOps.push(() =>
              Transaction.updateOne(
                { _id: existing._id },
                { $set: { amount: myAmount, myShare: mySplit?.amountBase || 0, totalExpenseAmount: expense.amountBase } }
              ).then(() => void 0)
            );
            synced++;
          } else {
            skipped++;
          }
          continue;
        }

        const splitNames = expense.splits
          .filter((s: any) => s.userId !== userId)
          .map((s: any) => s.displayName);

        bulkOps.push({
          insertOne: {
            document: {
              userId,
              type: 'trip_expense' as ITransaction['type'],
              amount: myAmount,
              currency: expense.baseCurrency,
              title: expense.title,
              category: expense.category,
              date: expense.date,
              paymentMethod: 'Other',
              notes: expense.notes,
              receiptImage: expense.receiptImages?.[0],
              tags: expense.tags || [],
              tripId: expense.tripId,
              tripName: tripMap.get(String(expense.tripId)),
              expenseId: expense._id,
              isAutoGenerated: true,
              myShare: mySplit?.amountBase || 0,
              totalExpenseAmount: expense.amountBase,
              splitWith: splitNames,
              location: expense.location,
              isDeleted: false,
            },
          },
        });
        synced++;
      }

      await Promise.all([
        bulkOps.length > 0 ? Transaction.bulkWrite(bulkOps, { ordered: false }) : Promise.resolve(),
        ...updateOps.map(op => op()),
        this.syncSettlementTransactions(userId),
      ]);

      logger.info(`Trip expenses synced for user ${userId}: ${synced} new/updated, ${skipped} skipped`);
      return { synced, skipped };
    } catch (error) {
      logger.error(`Error syncing trip expenses for user ${userId}:`, error);
      throw error;
    }
  }

  static async syncSettlementTransactions(userId: string): Promise<void> {
    try {
      const settlements = await Settlement.find({
        $or: [
          { 'transactions.from': userId },
          { 'transactions.to': userId },
        ],
      }).lean();

      if (settlements.length === 0) return;

      const settlementIds = settlements.map((s: any) => s._id);
      const existingSettlementTxns = await Transaction.find({
        userId,
        settlementId: { $in: settlementIds },
        isAutoGenerated: true,
      }).select('settlementId title').lean();

      const syncedKeys = new Set<string>();
      existingSettlementTxns.forEach((t: any) => {
        syncedKeys.add(`${String(t.settlementId)}:${t.title}`);
      });

      const toCreate: any[] = [];

      for (const settlement of settlements) {
        for (const txn of (settlement as any).transactions) {
          if (txn.status !== 'confirmed') continue;

          if (txn.from === userId) {
            const title = `Settlement: Paid ${txn.toName}`;
            if (!syncedKeys.has(`${String(settlement._id)}:${title}`)) {
              toCreate.push({
                userId,
                type: 'settlement_paid',
                amount: txn.amountBase,
                currency: txn.baseCurrency,
                title,
                category: 'settlement',
                date: txn.confirmedAt || new Date(),
                paymentMethod: 'UPI',
                notes: `Trip settlement payment to ${txn.toName}`,
                settlementId: settlement._id,
                isAutoGenerated: true,
                isDeleted: false,
              });
            }
          }

          if (txn.to === userId) {
            const title = `Settlement: Received from ${txn.fromName}`;
            if (!syncedKeys.has(`${String(settlement._id)}:${title}`)) {
              toCreate.push({
                userId,
                type: 'settlement_received',
                amount: txn.amountBase,
                currency: txn.baseCurrency,
                title,
                category: 'settlement',
                date: txn.confirmedAt || new Date(),
                paymentMethod: 'UPI',
                notes: `Trip settlement received from ${txn.fromName}`,
                settlementId: settlement._id,
                isAutoGenerated: true,
                isDeleted: false,
              });
            }
          }
        }
      }

      if (toCreate.length > 0) {
        await Transaction.insertMany(toCreate, { ordered: false });
      }
    } catch (error) {
      logger.error(`Error syncing settlement transactions for user ${userId}:`, error);
    }
  }

  // ============================================================
  // TRANSACTION CRUD
  // ============================================================

  static async createTransaction(userId: string, data: Partial<ITransaction>) {
    const txDate = data.date ? new Date(data.date) : new Date();
    const transaction = new Transaction({
      ...data,
      userId,
      date: txDate,
      isAutoGenerated: false,
    });
    await transaction.save();

    if (data.type === 'expense' && data.category) {
      const month = txDate.toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, month, data.category, data.amount || 0);
    }

    logger.info(`Transaction created: ${userId} - ${data.title}`);
    return transaction;
  }
  static async getTransactions(userId: string, filters: TransactionFilters = {}) {
    const query: any = { userId, isDeleted: false };

    // Basic filters
    if (filters.type) query.type = filters.type;
    if (filters.category) query.category = filters.category;
    if (filters.tripId) query.tripId = new Types.ObjectId(filters.tripId);
    if (filters.tags && filters.tags.length > 0) query.tags = { $in: filters.tags };
    
    // Search filter
    if (filters.search) {
      query.$or = [
        { title: { $regex: filters.search, $options: 'i' } },
        { notes: { $regex: filters.search, $options: 'i' } },
      ];
    }

    // Date filtering with multiple options
    if (filters.dateRange) {
      // Custom date range (highest priority)
      query.date = {};
      if (filters.dateRange.startDate) {
        query.date.$gte = new Date(filters.dateRange.startDate);
      }
      if (filters.dateRange.endDate) {
        query.date.$lte = new Date(filters.dateRange.endDate);
      }
    } else if (filters.day) {
      // Filter by specific day: YYYY-MM-DD
      const startDate = new Date(`${filters.day}T00:00:00.000Z`);
      const endDate = new Date(`${filters.day}T23:59:59.999Z`);
      query.date = { $gte: startDate, $lte: endDate };
    } else if (filters.month && filters.year) {
      // Filter by specific month and year: YYYY-MM
      const monthNum = parseInt(filters.month) - 1; // 0-indexed month
      const startDate = new Date(filters.year, monthNum, 1, 0, 0, 0, 0);
      const endDate = new Date(filters.year, monthNum + 1, 0, 23, 59, 59, 999);
      query.date = { $gte: startDate, $lte: endDate };
    } else if (filters.month) {
      // Filter by month (year defaults to current year)
      const currentYear = new Date().getFullYear();
      const monthNum = parseInt(filters.month) - 1;
      const startDate = new Date(currentYear, monthNum, 1, 0, 0, 0, 0);
      const endDate = new Date(currentYear, monthNum + 1, 0, 23, 59, 59, 999);
      query.date = { $gte: startDate, $lte: endDate };
    } else if (filters.year) {
      // Filter by specific year
      const startDate = new Date(filters.year, 0, 1, 0, 0, 0, 0);
      const endDate = new Date(filters.year, 11, 31, 23, 59, 59, 999);
      query.date = { $gte: startDate, $lte: endDate };
    } else if (filters.startDate || filters.endDate) {
      // Legacy date range filter (backward compatibility)
      query.date = {};
      if (filters.startDate) {
        query.date.$gte = new Date(filters.startDate);
      }
      if (filters.endDate) {
        query.date.$lte = new Date(filters.endDate);
      }
    }

    // Pagination
    const limit = Math.min(filters.limit || 50, 100);
    const page = Math.max(filters.page || 1, 1);
    const skip = (page - 1) * limit;
    const sortField = filters.sortBy || 'date';
    const sortOrder = filters.sortOrder === 'asc' ? 1 : -1;

    // Execute queries
    const [transactions, total, summary] = await Promise.all([
      Transaction.find(query)
        .sort({ [sortField]: sortOrder, createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate('tripId', 'title coverImage')
        .lean(),
      Transaction.countDocuments(query),
      Transaction.aggregate([
        { $match: query },
        {
          $group: {
            _id: null,
            totalExpense: { 
              $sum: { 
                $cond: [{ $in: ['$type', ['expense', 'trip_expense', 'settlement_paid']] }, '$amount', 0] 
              } 
            },
            totalIncome: { 
              $sum: { 
                $cond: [{ $in: ['$type', ['income', 'settlement_received']] }, '$amount', 0] 
              } 
            },
          },
        },
      ]),
    ]);

    return {
      transactions,
      summary: {
        totalExpense: summary[0]?.totalExpense || 0,
        totalIncome: summary[0]?.totalIncome || 0,
        netAmount: (summary[0]?.totalIncome || 0) - (summary[0]?.totalExpense || 0),
      },
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
        hasMore: skip + transactions.length < total,
      },
    };
  }
  
  // static async getTransactions(userId: string, filters: TransactionFilters = {}) {
  //   const query: any = { userId, isDeleted: false };

  //   if (filters.type) query.type = filters.type;
  //   if (filters.category) query.category = filters.category;
  //   if (filters.tripId) query.tripId = new Types.ObjectId(filters.tripId);
  //   if (filters.tags && filters.tags.length > 0) query.tags = { $in: filters.tags };
  //   if (filters.search) {
  //     query.$or = [
  //       { title: { $regex: filters.search, $options: 'i' } },
  //       { notes: { $regex: filters.search, $options: 'i' } },
  //     ];
  //   }

  //   if (filters.month) {
  //     const startDate = new Date(`${filters.month}-01T00:00:00.000Z`);
  //     const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);
  //     query.date = { $gte: startDate, $lte: endDate };
  //   } else if (filters.startDate || filters.endDate) {
  //     query.date = {};
  //     if (filters.startDate) query.date.$gte = new Date(filters.startDate);
  //     if (filters.endDate) query.date.$lte = new Date(filters.endDate);
  //   }

  //   const limit = Math.min(filters.limit || 50, 100);
  //   const page = Math.max(filters.page || 1, 1);
  //   const skip = (page - 1) * limit;
  //   const sortField = filters.sortBy || 'date';
  //   const sortOrder = filters.sortOrder === 'asc' ? 1 : -1;

  //   const [transactions, total, summary] = await Promise.all([
  //     Transaction.find(query)
  //       .sort({ [sortField]: sortOrder, createdAt: -1 })
  //       .skip(skip)
  //       .limit(limit)
  //       .populate('tripId', 'title coverImage')
  //       .lean(),
  //     Transaction.countDocuments(query),
  //     Transaction.aggregate([
  //       { $match: query },
  //       {
  //         $group: {
  //           _id: null,
  //           totalExpense: { $sum: { $cond: [{ $in: ['$type', ['expense', 'trip_expense', 'settlement_paid']] }, '$amount', 0] } },
  //           totalIncome: { $sum: { $cond: [{ $in: ['$type', ['income', 'settlement_received']] }, '$amount', 0] } },
  //         },
  //       },
  //     ]),
  //   ]);

  //   return {
  //     transactions,
  //     summary: {
  //       totalExpense: summary[0]?.totalExpense || 0,
  //       totalIncome: summary[0]?.totalIncome || 0,
  //       netAmount: (summary[0]?.totalIncome || 0) - (summary[0]?.totalExpense || 0),
  //     },
  //     pagination: {
  //       page,
  //       limit,
  //       total,
  //       totalPages: Math.ceil(total / limit),
  //       hasMore: skip + transactions.length < total,
  //     },
  //   };
  // }

  static async getTransactionById(userId: string, transactionId: string) {
    const transaction = await Transaction.findOne({
      _id: transactionId,
      userId,
      isDeleted: false,
    }).populate('tripId', 'title coverImage');

    if (!transaction) throw new AppError('Transaction not found', 404);
    return transaction;
  }

  static async updateTransaction(userId: string, transactionId: string, data: Partial<ITransaction>) {
    const transaction = await Transaction.findOne({
      _id: transactionId,
      userId,
      isDeleted: false,
    });

    if (!transaction) throw new AppError('Transaction not found', 404);

    const oldAmount = transaction.amount;
    const oldCategory = transaction.category;
    const oldType = transaction.type;
    const oldDate = transaction.date;

    if (transaction.isAutoGenerated && (data.amount || data.category)) {
      throw new AppError('Trip expenses are auto-managed. Update the expense in the trip instead.', 400);
    }

    Object.assign(transaction, data);
    await transaction.save();

    if (oldType === 'expense' || oldType === 'trip_expense') {
      const oldMonth = new Date(oldDate).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, oldMonth, oldCategory, -oldAmount);
    }

    if ((data.type === 'expense' || transaction.type === 'expense') && transaction.category) {
      const newMonth = new Date(data.date || oldDate).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, newMonth, transaction.category, data.amount || transaction.amount);
    }

    return transaction;
  }

  static async deleteTransaction(userId: string, transactionId: string, permanent: boolean = false) {
    const transaction = await Transaction.findOne({ _id: transactionId, userId });

    if (!transaction) throw new AppError('Transaction not found', 404);

    if (permanent) {
      if ((transaction.type === 'expense' || transaction.type === 'trip_expense') && transaction.category) {
        const month = new Date(transaction.date).toISOString().substring(0, 7);
        await this.updateBudgetSpent(userId, month, transaction.category, -transaction.amount);
      }
      await transaction.deleteOne();
    } else {
      transaction.isDeleted = true;
      transaction.deletedAt = new Date();
      await transaction.save();
    }

    return { success: true, message: 'Transaction deleted successfully' };
  }

  static async restoreTransaction(userId: string, transactionId: string) {
    const transaction = await Transaction.findOne({
      _id: transactionId,
      userId,
      isDeleted: true,
    });

    if (!transaction) throw new AppError('Transaction not found', 404);

    transaction.isDeleted = false;
    transaction.deletedAt = undefined;
    await transaction.save();

    if ((transaction.type === 'expense' || transaction.type === 'trip_expense') && transaction.category) {
      const month = new Date(transaction.date).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, month, transaction.category, transaction.amount);
    }

    return transaction;
  }

  // ============================================================
  // BUDGET
  // ============================================================

  static async setBudget(
    userId: string,
    month: string,
    totalBudget: number,
    categoryBudgets: { category: string; amount: number; color?: string }[] = []
  ) {
    const startDate = new Date(`${month}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

    const transactions = await Transaction.find({
      userId,
      type: { $in: ['expense', 'trip_expense'] },
      date: { $gte: startDate, $lte: endDate },
      isDeleted: false,
    });

    const categorySpent: Record<string, number> = {};
    let totalSpent = 0;
    transactions.forEach(t => {
      categorySpent[t.category] = (categorySpent[t.category] || 0) + t.amount;
      totalSpent += t.amount;
    });

    const categoryBudgetsWithSpent = categoryBudgets.map(cb => ({
      category: cb.category,
      amount: cb.amount,
      spent: categorySpent[cb.category] || 0,
      color: cb.color,
    }));

    const budget = await Budget.findOneAndUpdate(
      { userId, month },
      {
        totalBudget,
        totalSpent,
        categoryBudgets: categoryBudgetsWithSpent,
      },
      { upsert: true, new: true }
    );

    return budget;
  }

  static async getBudget(userId: string, month: string, precomputedTotal?: number) {
    let budget = await Budget.findOne({ userId, month });

    const totalSpent = precomputedTotal !== undefined
      ? precomputedTotal
      : await this.getTotalExpenseForMonth(userId, month);

    if (!budget) {
      budget = await Budget.create({
        userId,
        month,
        totalBudget: 0,
        totalSpent,
        categoryBudgets: [],
      });
    } else if (budget.totalSpent !== totalSpent) {
      budget.totalSpent = totalSpent;
      await budget.save();
    }

    return budget;
  }

  static async updateBudget(
    userId: string,
    budgetId: string,
    totalBudget?: number,
    categoryBudgets?: { category: string; amount: number; color?: string }[]
  ): Promise<IBudget> {
    const budget = await Budget.findOne({ _id: budgetId, userId });
    if (!budget) {
      throw new AppError('Budget not found', 404);
    }

    const month = budget.month;
    const startDate = new Date(`${month}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

    const transactions = await Transaction.find({
      userId,
      type: { $in: ['expense', 'trip_expense'] },
      date: { $gte: startDate, $lte: endDate },
      isDeleted: false,
    });

    const categorySpent: Record<string, number> = {};
    let totalSpent = 0;
    transactions.forEach(t => {
      categorySpent[t.category] = (categorySpent[t.category] || 0) + t.amount;
      totalSpent += t.amount;
    });

    if (totalBudget !== undefined) {
      budget.totalBudget = totalBudget;
    }

    if (categoryBudgets) {
      budget.categoryBudgets = categoryBudgets.map(cb => ({
        category: cb.category,
        amount: cb.amount,
        spent: categorySpent[cb.category] || 0,
        color: cb.color,
      }));
    }

    budget.totalSpent = totalSpent;
    await budget.save();

    return budget;
  }

  static async deleteBudget(userId: string, budgetId: string) {
    const budget = await Budget.findOne({ _id: budgetId, userId });
    if (!budget) {
      throw new AppError('Budget not found', 404);
    }

    await budget.deleteOne();
    return {
      success: true,
      message: 'Budget deleted successfully',
      deletedBudget: budget
    };
  }

  static async updateBudgetSpent(userId: string, month: string, category: string, amountDelta: number) {
    if (amountDelta === 0) return;

    const budget = await Budget.findOne({ userId, month });
    if (!budget) return;

    const catBudget = budget.categoryBudgets.find(cb => cb.category === category);
    if (catBudget) {
      catBudget.spent = Math.max(0, (catBudget.spent || 0) + amountDelta);
    }

    budget.totalSpent = Math.max(0, (budget.totalSpent || 0) + amountDelta);
    await budget.save();
  }

  static async getTotalExpenseForMonth(userId: string, month: string): Promise<number> {
    const startDate = new Date(`${month}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

    const result = await Transaction.aggregate([
      {
        $match: {
          userId,
          type: { $in: ['expense', 'trip_expense', 'settlement_paid'] },
          date: { $gte: startDate, $lte: endDate },
          isDeleted: false,
        },
      },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]);

    return result[0]?.total || 0;
  }

  // ============================================================
  // BILLS
  // ============================================================

  static async createBill(userId: string, data: Partial<IBill>) {
    const bill = new Bill({
      ...data,
      userId,
      nextDueDate: data.dueDate,
    });
    await bill.save();
    return bill;
  }

  static async lazyAdvanceBills(userId: string) {
    const now = new Date();
    // Only fetch bills that are paid and where dueDate is in the past
    const bills = await Bill.find({ userId, isPaid: true, dueDate: { $lt: now } });
    for (const bill of bills) {
      if (!bill.frequency || (bill.frequency as string) === 'one-time' || (bill.frequency as string) === 'none') continue;

      let shouldAdvance = false;
      const dueDate = new Date(bill.dueDate);

      if (bill.frequency === 'monthly') {
        if (now.getMonth() !== dueDate.getMonth() || now.getFullYear() !== dueDate.getFullYear()) {
          shouldAdvance = true;
        }
      } else if (bill.frequency === 'yearly') {
        if (now.getFullYear() !== dueDate.getFullYear()) {
          shouldAdvance = true;
        }
      } else if (bill.frequency === 'weekly') {
        // If more than 7 days have passed since dueDate
        const daysPassed = (now.getTime() - dueDate.getTime()) / (1000 * 3600 * 24);
        if (daysPassed >= 7) {
          shouldAdvance = true;
        }
      } else if (bill.frequency === 'daily') {
        const daysPassed = (now.getTime() - dueDate.getTime()) / (1000 * 3600 * 24);
        if (daysPassed >= 1) {
          shouldAdvance = true;
        }
      }

      if (shouldAdvance) {
        const nextDate = new Date(bill.dueDate);
        switch (bill.frequency) {
          case 'monthly': nextDate.setMonth(nextDate.getMonth() + 1); break;
          case 'weekly': nextDate.setDate(nextDate.getDate() + 7); break;
          case 'yearly': nextDate.setFullYear(nextDate.getFullYear() + 1); break;
          case 'daily': nextDate.setDate(nextDate.getDate() + 1); break;
        }
        bill.dueDate = nextDate;
        bill.nextDueDate = nextDate;
        bill.isPaid = false;
        bill.paidThisMonth = false;
        await bill.save();
      }
    }
  }

  static async getBills(
    userId: string, 
    filters: { 
      isActive?: boolean | string; 
      category?: string; 
      upcoming?: boolean | string; 
      isPaid?: boolean | string;
      search?: string;
      dateFilter?: string;
      startDate?: string;
      endDate?: string;
      page?: string | number;
      limit?: string | number;
    } = {}
  ) {
    await this.lazyAdvanceBills(userId);
    const query: any = { userId };
    
    if (filters.isActive !== undefined) {
      query.isActive = filters.isActive === 'true' || filters.isActive === true;
    }
    
    if (filters.category && filters.category !== 'All') {
      query.category = filters.category;
    }
    
    if (filters.isPaid !== undefined) {
      query.isPaid = filters.isPaid === 'true' || filters.isPaid === true;
    }
    
    if (filters.upcoming) {
      query.dueDate = { $gte: new Date() };
      query.isPaid = false;
    }

    if (filters.search) {
      query.title = { $regex: filters.search, $options: 'i' };
    }

    // Date filters (This Month, Next Month, Past)
    if (filters.dateFilter && filters.dateFilter !== 'All Time') {
      const now = new Date();
      if (filters.dateFilter === 'This Month') {
        const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
        const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);
        query.dueDate = { ...query.dueDate, $gte: startOfMonth, $lte: endOfMonth };
      } else if (filters.dateFilter === 'Next Month') {
        const startOfNextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1);
        const endOfNextMonth = new Date(now.getFullYear(), now.getMonth() + 2, 0, 23, 59, 59, 999);
        query.dueDate = { ...query.dueDate, $gte: startOfNextMonth, $lte: endOfNextMonth };
      } else if (filters.dateFilter === 'Past') {
        const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
        query.dueDate = { ...query.dueDate, $lt: startOfMonth };
      }
    }

    // Specific Date Range
    if (filters.startDate || filters.endDate) {
      query.dueDate = query.dueDate || {};
      if (filters.startDate) query.dueDate.$gte = new Date(filters.startDate);
      if (filters.endDate) query.dueDate.$lte = new Date(filters.endDate);
    }

    // Pagination
    const page = parseInt(filters.page as string) || 1;
    const limit = parseInt(filters.limit as string) || 20;
    const skip = (page - 1) * limit;

    const total = await Bill.countDocuments(query);
    const bills = await Bill.find(query).sort({ dueDate: 1 }).skip(skip).limit(limit).lean();

    return {
      bills,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    };
  }

  static async getBillById(userId: string, billId: string) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);
    return bill;
  }

  static async updateBill(userId: string, billId: string, data: Partial<IBill>) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);

    Object.assign(bill, data);
    await bill.save();
    return bill;
  }

  static async markBillPaid(userId: string, billId: string, paidAmount?: number) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);

    bill.isPaid = true;
    bill.paidThisMonth = true;
    bill.paidAmount = paidAmount || bill.amount;
    bill.lastPaidDate = new Date();

    // We do NOT advance the dueDate immediately here so the bill shows as "Paid" 
    // for the current cycle on the frontend. It will be lazily advanced in getBills().

    await bill.save();

    await this.createTransaction(userId, {
      type: 'expense',
      amount: paidAmount || bill.amount,
      currency: bill.currency,
      title: `Bill: ${bill.title}`,
      category: bill.category,
      date: new Date(),
      paymentMethod: 'UPI',
      notes: `Bill payment - ${bill.title}`,
      isAutoGenerated: true,
    });

    return bill;
  }

  static async skipBill(userId: string, billId: string) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);

    const nextDate = new Date(bill.dueDate);
    switch (bill.frequency) {
      case 'monthly': nextDate.setMonth(nextDate.getMonth() + 1); break;
      case 'weekly': nextDate.setDate(nextDate.getDate() + 7); break;
      case 'yearly': nextDate.setFullYear(nextDate.getFullYear() + 1); break;
      default: nextDate.setMonth(nextDate.getMonth() + 1);
    }

    bill.dueDate = nextDate;
    bill.nextDueDate = nextDate;
    bill.isPaid = false;
    bill.paidThisMonth = false;
    bill.notes = bill.notes
      ? `${bill.notes}\nSkipped on ${new Date().toISOString().split('T')[0]}`
      : `Skipped on ${new Date().toISOString().split('T')[0]}`;

    await bill.save();
    return bill;
  }

  static async deleteBill(userId: string, billId: string) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);
    await bill.deleteOne();
    return { success: true, message: 'Bill deleted' };
  }

  // ============================================================
  // GOALS
  // ============================================================

  static async createGoal(userId: string, data: Partial<IGoal>) {
    const goal = new Goal({ ...data, userId });
    await goal.save();
    return goal;
  }

  static async getGoals(userId: string, filters: { isCompleted?: boolean } = {}) {
    const query: any = { userId };
    if (filters.isCompleted !== undefined) query.isCompleted = filters.isCompleted;
    return Goal.find(query).sort({ targetDate: 1 }).lean();
  }

  static async getGoalById(userId: string, goalId: string) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);
    return goal;
  }

  static async updateGoal(userId: string, goalId: string, data: Partial<IGoal>) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);

    Object.assign(goal, data);
    await goal.save();
    return goal;
  }

  static async contributeToGoal(userId: string, goalId: string, amount: number) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);
    if (goal.isCompleted) throw new AppError('Goal already completed', 400);

    goal.savedAmount += amount;
    await goal.save();

    await this.createTransaction(userId, {
      type: 'expense',
      amount,
      currency: goal.currency,
      title: `Goal Contribution: ${goal.title}`,
      category: 'savings',
      date: new Date(),
      paymentMethod: 'Other',
      notes: `Contribution to goal: ${goal.title}`,
      isAutoGenerated: true,
    });

    return goal;
  }

  static async deleteGoal(userId: string, goalId: string) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);
    await goal.deleteOne();
    return { success: true, message: 'Goal deleted' };
  }

  // ============================================================
  // DASHBOARD & ANALYTICS
  // ============================================================

  static async getDashboard(userId: string, month?: string, includeTripExpenses: boolean = true) {
    const targetMonth = month || new Date().toISOString().substring(0, 7);
    const startDate = new Date(`${targetMonth}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);
    const lastMonthStart = new Date(startDate.getFullYear(), startDate.getMonth() - 1, 1);
    const lastMonthEnd = new Date(startDate.getFullYear(), startDate.getMonth(), 0, 23, 59, 59, 999);

    if (includeTripExpenses) {
      this.syncTripExpenses(userId).catch(err =>
        logger.warn('Background sync failed for dashboard', { userId, err: err.message })
      );
    }

    const [aggregateResult, goals, bills, completedGoalCount] = await Promise.all([
      Transaction.aggregate([
        {
          $match: {
            userId,
            isDeleted: false,
            date: { $gte: lastMonthStart, $lte: endDate },
          },
        },
        {
          $facet: {
            currentMonth: [
              { $match: { date: { $gte: startDate, $lte: endDate } } },
              {
                $group: {
                  _id: '$type',
                  total: { $sum: '$amount' },
                  count: { $sum: 1 },
                },
              },
            ],
            lastMonth: [
              { $match: { date: { $gte: lastMonthStart, $lte: lastMonthEnd } } },
              {
                $group: {
                  _id: '$type',
                  total: { $sum: '$amount' },
                },
              },
            ],
            categorySpending: [
              { $match: { date: { $gte: startDate, $lte: endDate }, type: { $in: ['expense', 'trip_expense'] } } },
              {
                $group: {
                  _id: '$category',
                  spent: { $sum: '$amount' },
                },
              },
            ],
            dailySpending: [
              { $match: { date: { $gte: startDate, $lte: endDate }, type: { $in: ['expense', 'trip_expense'] } } },
              {
                $group: {
                  _id: { $dateToString: { format: '%Y-%m-%d', date: '$date' } },
                  total: { $sum: '$amount' },
                },
              },
            ],
            recentTransactions: [
              { $match: { date: { $gte: startDate, $lte: endDate } } },
              { $sort: { date: -1 } },
              { $limit: 10 },
            ],
          },
        },
      ]),
      Goal.find({ userId, isCompleted: false }).sort({ targetDate: 1 }).lean(),
      Bill.find({ userId, isActive: true }).sort({ dueDate: 1 }).lean(),
      Goal.countDocuments({ userId, isCompleted: true }),
    ]);

    const facet = aggregateResult[0];

    const currentByType: Record<string, number> = {};
    const currentCount: Record<string, number> = {};
    for (const row of facet.currentMonth) {
      currentByType[row._id] = row.total;
      currentCount[row._id] = row.count;
    }

    const lastByType: Record<string, number> = {};
    for (const row of facet.lastMonth) {
      lastByType[row._id] = row.total;
    }

    const totalIncome = (currentByType['income'] || 0) + (currentByType['settlement_received'] || 0);
    const totalExpense = (currentByType['expense'] || 0) + (currentByType['trip_expense'] || 0);
    const tripExpenses = currentByType['trip_expense'] || 0;
    const manualExpenses = currentByType['expense'] || 0;
    const settlementsPaid = currentByType['settlement_paid'] || 0;
    const settlementsReceived = currentByType['settlement_received'] || 0;

    const lastMonthExpense = (lastByType['expense'] || 0) + (lastByType['trip_expense'] || 0) + (lastByType['settlement_paid'] || 0);
    const lastMonthIncome = (lastByType['income'] || 0) + (lastByType['settlement_received'] || 0);

    const totalTransactionCount = Object.values(currentCount).reduce((s, c) => s + c, 0);

    const categorySpendingMap: Record<string, number> = {};
    for (const row of facet.categorySpending) {
      categorySpendingMap[row._id] = row.spent;
    }

    const totalExpenseForBudget = totalExpense + settlementsPaid;
    const budget = await this.getBudget(userId, targetMonth, totalExpenseForBudget);
    const totalBudget = budget?.totalBudget || 0;

    const categoryBreakdown = Object.entries(categorySpendingMap)
      .map(([category, spent]) => {
        const budgetForCategory = budget?.categoryBudgets?.find((cb: any) => cb.category === category);
        return {
          category,
          spent: Math.round(spent * 100) / 100,
          budget: budgetForCategory?.amount || 0,
          budgetRemaining: (budgetForCategory?.amount || 0) - spent,
          percentOfTotal: totalExpense > 0 ? Math.round((spent / totalExpense) * 100) : 0,
          isOverBudget: budgetForCategory ? spent > budgetForCategory.amount : false,
        };
      })
      .sort((a, b) => b.spent - a.spent);

    const topCategory = categoryBreakdown[0] || { category: 'none', spent: 0, percentOfTotal: 0 };

    const daysInMonth = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0).getDate();
    const daysElapsed = Math.min(new Date().getDate(), daysInMonth);
    const averageDailyExpense = daysElapsed > 0 ? totalExpense / daysElapsed : 0;

    const expensesChange = lastMonthExpense > 0
      ? Math.round(((totalExpense - lastMonthExpense) / lastMonthExpense) * 100)
      : 0;
    const incomeChange = lastMonthIncome > 0
      ? Math.round(((totalIncome - lastMonthIncome) / lastMonthIncome) * 100)
      : 0;
    const netCurrent = totalIncome - totalExpense;
    const netLast = lastMonthIncome - lastMonthExpense;
    const savingsChange = netLast !== 0
      ? Math.round(((netCurrent - netLast) / Math.abs(netLast)) * 100)
      : 0;

    const upcomingBills = bills.filter((b: any) => {
      const daysUntilDue = Math.ceil((new Date(b.dueDate).getTime() - Date.now()) / 86400000);
      return daysUntilDue <= 7 && daysUntilDue >= 0 && !b.paidThisMonth;
    });

    return {
      monthlyOverview: {
        month: targetMonth,
        totalIncome: Math.round(totalIncome * 100) / 100,
        totalExpense: Math.round(totalExpense * 100) / 100,
        netSavings: Math.round((totalIncome - totalExpense) * 100) / 100,
        budget: totalBudget,
        budgetSpent: budget?.totalSpent || 0,
        budgetRemaining: totalBudget - (budget?.totalSpent || 0),
        budgetUsedPercent: totalBudget > 0 ? Math.round(((budget?.totalSpent || 0) / totalBudget) * 100) : 0,
        averageDailyExpense: Math.round(averageDailyExpense * 100) / 100,
        tripExpenses: Math.round(tripExpenses * 100) / 100,
        manualExpenses: Math.round(manualExpenses * 100) / 100,
        settlementsPaid: Math.round(settlementsPaid * 100) / 100,
        settlementsReceived: Math.round(settlementsReceived * 100) / 100,
        comparedToLastMonth: { expensesChange, incomeChange, savingsChange },
      },
      categoryBreakdown,
      topSpendingCategory: {
        category: topCategory.category,
        amount: topCategory.spent,
        percentOfTotal: topCategory.percentOfTotal || 0,
      },
      recentTransactions: facet.recentTransactions,
      goals: {
        active: goals.length,
        completed: completedGoalCount,
        items: goals.slice(0, 5),
        totalTarget: goals.reduce((s: number, g: any) => s + g.targetAmount, 0),
        totalSaved: goals.reduce((s: number, g: any) => s + g.savedAmount, 0),
      },
      bills: {
        total: bills.length,
        upcoming: upcomingBills,
        upcomingCount: upcomingBills.length,
        totalDueThisMonth: bills
          .filter((b: any) => !b.paidThisMonth)
          .reduce((s: number, b: any) => s + b.amount, 0),
      },
      stats: {
        transactionCount: totalTransactionCount,
        daysWithExpenses: facet.dailySpending.length,
      },
    };
  }

  static async getAnalytics(userId: string, filters: AnalyticsFilters = {}) {
    let startDate: Date;
    let endDate: Date = new Date();

    switch (filters.period) {
      case 'week':
        startDate = new Date(Date.now() - 7 * 86400000);
        break;
      case 'month':
        startDate = new Date(Date.now() - 30 * 86400000);
        break;
      case 'quarter':
        startDate = new Date(Date.now() - 90 * 86400000);
        break;
      case 'year':
        startDate = new Date(Date.now() - 365 * 86400000);
        break;
      case 'all':
        startDate = new Date(0);
        break;
      default:
        startDate = filters.startDate ? new Date(filters.startDate) : new Date(Date.now() - 30 * 86400000);
        endDate = filters.endDate ? new Date(filters.endDate) : new Date();
    }

    const transactions = await Transaction.find({
      userId,
      date: { $gte: startDate, $lte: endDate },
      isDeleted: false,
      type: { $in: ['expense', 'trip_expense'] },
    }).sort({ date: 1 }).lean();

    const dailyTrend: Record<string, number> = {};
    transactions.forEach(t => {
      const key = new Date(t.date).toISOString().split('T')[0];
      dailyTrend[key] = (dailyTrend[key] || 0) + t.amount;
    });

    const categoryDistribution: Record<string, number> = {};
    transactions.forEach(t => {
      categoryDistribution[t.category] = (categoryDistribution[t.category] || 0) + t.amount;
    });

    const totalSpent = transactions.reduce((s, t) => s + t.amount, 0);

    const paymentMethods: Record<string, number> = {};
    transactions.forEach(t => {
      const method = t.paymentMethod || 'Other';
      paymentMethods[method] = (paymentMethods[method] || 0) + t.amount;
    });

    const tripExpenseTotal = transactions
      .filter(t => t.type === 'trip_expense')
      .reduce((s, t) => s + t.amount, 0);
    const manualExpenseTotal = transactions
      .filter(t => t.type === 'expense')
      .reduce((s, t) => s + t.amount, 0);

    const monthlyTrend: Record<string, number> = {};
    transactions.forEach(t => {
      const key = new Date(t.date).toISOString().substring(0, 7);
      monthlyTrend[key] = (monthlyTrend[key] || 0) + t.amount;
    });

    return {
      period: {
        startDate,
        endDate,
        days: Math.ceil((endDate.getTime() - startDate.getTime()) / 86400000),
      },
      overview: {
        totalSpent: Math.round(totalSpent * 100) / 100,
        averagePerTransaction: transactions.length > 0
          ? Math.round((totalSpent / transactions.length) * 100) / 100
          : 0,
        transactionCount: transactions.length,
        averageDaily: Math.round((totalSpent / Math.max(1, Math.ceil((endDate.getTime() - startDate.getTime()) / 86400000))) * 100) / 100,
      },
      dailyTrend: Object.entries(dailyTrend).map(([date, amount]) => ({
        date,
        amount: Math.round(amount * 100) / 100,
      })).sort((a, b) => a.date.localeCompare(b.date)),
      monthlyTrend: Object.entries(monthlyTrend).map(([month, amount]) => ({
        month,
        amount: Math.round(amount * 100) / 100,
      })).sort((a, b) => a.month.localeCompare(b.month)),
      categoryDistribution: Object.entries(categoryDistribution)
        .map(([category, amount]) => ({
          category,
          amount: Math.round(amount * 100) / 100,
          percent: totalSpent > 0 ? Math.round((amount / totalSpent) * 100) : 0,
        }))
        .sort((a, b) => b.amount - a.amount),
      paymentMethods: Object.entries(paymentMethods)
        .map(([method, amount]) => ({
          method,
          amount: Math.round(amount * 100) / 100,
          percent: totalSpent > 0 ? Math.round((amount / totalSpent) * 100) : 0,
        }))
        .sort((a, b) => b.amount - a.amount),
      tripVsManual: {
        tripExpenses: Math.round(tripExpenseTotal * 100) / 100,
        manualExpenses: Math.round(manualExpenseTotal * 100) / 100,
        tripPercent: totalSpent > 0 ? Math.round((tripExpenseTotal / totalSpent) * 100) : 0,
        manualPercent: totalSpent > 0 ? Math.round((manualExpenseTotal / totalSpent) * 100) : 0,
      },
    };
  }

  // ============================================================
  // ADDITIONAL FEATURES
  // ============================================================

  static async getBudgetCategories(userId: string) {
    const categories = await Transaction.aggregate([
      {
        $match: {
          userId,
          isDeleted: false,
          type: { $in: ['expense', 'trip_expense', 'settlement_paid'] },
        },
      },
      {
        $group: {
          _id: '$category',
          totalSpent: { $sum: '$amount' },
          count: { $sum: 1 },
        },
      },
      { $sort: { totalSpent: -1 } },
    ]);

    const currentMonth = new Date().toISOString().substring(0, 7);
    const budget = await Budget.findOne({ userId, month: currentMonth });

    return categories.map(c => ({
      category: c._id,
      totalSpent: c.totalSpent,
      count: c.count,
      budgetAmount: budget?.categoryBudgets?.find((b: any) => b.category === c._id)?.amount || 0,
      budgetSpent: budget?.categoryBudgets?.find((b: any) => b.category === c._id)?.spent || 0,
    }));
  }

  static async bulkDeleteTransactions(userId: string, transactionIds: string[]) {
    if (!transactionIds || transactionIds.length === 0) {
      throw new AppError('No transaction IDs provided', 400);
    }

    const transactions = await Transaction.find({
      _id: { $in: transactionIds },
      userId,
      isDeleted: false,
    });

    if (transactions.length === 0) {
      throw new AppError('No valid transactions found', 404);
    }

    const now = new Date();
    const result = await Transaction.updateMany(
      { _id: { $in: transactionIds }, userId },
      {
        $set: {
          isDeleted: true,
          deletedAt: now,
        },
      }
    );

    for (const transaction of transactions) {
      if ((transaction.type === 'expense' || transaction.type === 'trip_expense') && transaction.category) {
        const month = new Date(transaction.date).toISOString().substring(0, 7);
        await this.updateBudgetSpent(userId, month, transaction.category, -transaction.amount);
      }
    }

    return {
      success: true,
      deletedCount: result.modifiedCount,
      totalRequested: transactionIds.length,
      message: `${result.modifiedCount} transactions deleted successfully`,
    };
  }

  static async getSpendingTrends(userId: string, months: number = 6, category?: string) {
    const endDate = new Date();
    const startDate = new Date();
    startDate.setMonth(startDate.getMonth() - months);

    const match: any = {
      userId,
      isDeleted: false,
      date: { $gte: startDate, $lte: endDate },
      type: { $in: ['expense', 'trip_expense', 'settlement_paid'] },
    };

    if (category) match.category = category;

    const trends = await Transaction.aggregate([
      { $match: match },
      {
        $group: {
          _id: {
            month: { $dateToString: { format: '%Y-%m', date: '$date' } },
            category: '$category',
          },
          total: { $sum: '$amount' },
        },
      },
      {
        $group: {
          _id: '$_id.month',
          categories: {
            $push: {
              category: '$_id.category',
              amount: '$total',
            },
          },
          total: { $sum: '$total' },
        },
      },
      { $sort: { _id: 1 } },
    ]);

    const allCategories = new Set<string>();
    trends.forEach(t => t.categories.forEach((c: any) => allCategories.add(c.category)));

    const result = trends.map(t => ({
      month: t._id,
      total: t.total,
      categories: Array.from(allCategories).map(cat => ({
        category: cat,
        amount: t.categories.find((c: any) => c.category === cat)?.amount || 0,
      })),
    }));

    return {
      trends: result,
      categories: Array.from(allCategories),
      period: {
        startDate,
        endDate,
        months,
      },
    };
  }

  static async createDebt(userId: string, data: any) {
    const debt = new Debt({ ...data, userId });
    await debt.save();
    return debt;
  }

  static async settleDebt(userId: string, debtId: string) {
    const debt = await Debt.findOneAndUpdate(
      { _id: debtId, $or: [{ userId }, { friendUserId: userId }] },
      { status: 'settled' },
      { new: true }
    );
    if (!debt) throw new Error('Debt not found');
    return debt;
  }

  static async getDebtSummary(userId: string, includeTrips: boolean = true) {
    const summary = {
      totalOwed: 0,
      totalOwing: 0,
      pendingOwed: 0,
      pendingOwing: 0,
      byTrip: [] as any[],
      byUser: [] as any[],
    };

    const userMap = new Map<string, { name: string; owes: number; owed: number }>();

    // 1. Independent Debts
    const independentDebts = await Debt.find({
      $or: [{ userId }, { friendUserId: userId }],
    });

    independentDebts.forEach(debt => {
      const isOwner = debt.userId === userId;
      let iOwe = false;
      let iAmOwed = false;
      let otherUserId = isOwner ? debt.friendUserId : debt.userId;
      let otherUserName = isOwner ? debt.name || 'Unknown' : 'User'; 

      if (isOwner && debt.type === 'lent') iAmOwed = true;
      else if (isOwner && debt.type === 'borrowed') iOwe = true;
      else if (!isOwner && debt.type === 'lent') iOwe = true;
      else if (!isOwner && debt.type === 'borrowed') iAmOwed = true;

      if (iAmOwed) {
        summary.totalOwed += debt.amount;
        if (debt.status === 'pending') summary.pendingOwed += debt.amount;

        if (otherUserId || otherUserName) {
          const key = otherUserId || otherUserName;
          if (!userMap.has(key)) userMap.set(key, { name: otherUserName, owes: 0, owed: 0 });
          userMap.get(key)!.owes += debt.amount;
        }
      } else if (iOwe) {
        summary.totalOwing += debt.amount;
        if (debt.status === 'pending') summary.pendingOwing += debt.amount;

        if (otherUserId || otherUserName) {
          const key = otherUserId || otherUserName;
          if (!userMap.has(key)) userMap.set(key, { name: otherUserName, owes: 0, owed: 0 });
          userMap.get(key)!.owed += debt.amount;
        }
      }
    });

    // 2. Trip Settlements (if included)
    if (includeTrips) {
      const settlements = await Settlement.find({
        $or: [
          { 'transactions.from': userId },
          { 'transactions.to': userId },
        ],
      }).populate('tripId', 'title baseCurrency');

      settlements.forEach(settlement => {
        const tripSummary = {
          tripId: (settlement.tripId as any)._id,
          tripName: (settlement.tripId as any).title,
          owed: 0,
          owing: 0,
          pendingOwed: 0,
          pendingOwing: 0,
        };

        settlement.transactions.forEach((tx: any) => {
          if (tx.from === userId) {
            const amount = tx.amountBase;
            tripSummary.owing += amount;
            summary.totalOwing += amount;
            if (tx.status === 'pending') {
              tripSummary.pendingOwing += amount;
              summary.pendingOwing += amount;
            }

            if (!userMap.has(tx.to)) {
              userMap.set(tx.to, { name: tx.toName, owes: 0, owed: 0 });
            }
            userMap.get(tx.to)!.owed += amount;
          }

          if (tx.to === userId) {
            const amount = tx.amountBase;
            tripSummary.owed += amount;
            summary.totalOwed += amount;
            if (tx.status === 'pending') {
              tripSummary.pendingOwed += amount;
              summary.pendingOwed += amount;
            }

            if (!userMap.has(tx.from)) {
              userMap.set(tx.from, { name: tx.fromName, owes: 0, owed: 0 });
            }
            userMap.get(tx.from)!.owes += amount;
          }
        });

        if (tripSummary.owed > 0 || tripSummary.owing > 0) {
          summary.byTrip.push(tripSummary);
        }
      });
    }

    summary.byUser = Array.from(userMap.entries()).map(([uId, data]) => ({
      userId: uId,
      ...data,
      net: data.owes - data.owed,
    }));

    return summary;
  }

  static async getDebtDetails(userId: string, tripId?: string, status?: string, includeTrips: boolean = true) {
    const transactions: any[] = [];

    // 1. Independent Debts
    const independentDebts = await Debt.find({
      $or: [{ userId }, { friendUserId: userId }],
    });

    independentDebts.forEach(debt => {
      if (status && debt.status !== status) return;
      if (tripId) return; 
      
      const isOwner = debt.userId === userId;
      let from = isOwner && debt.type === 'borrowed' ? userId : (debt.friendUserId || debt.name);
      let to = isOwner && debt.type === 'lent' ? userId : (debt.friendUserId || debt.name);
      
      transactions.push({
        _id: debt._id,
        amountBase: debt.amount,
        amount: debt.amount,
        currency: debt.currency,
        from,
        to,
        fromName: from === userId ? 'You' : debt.name,
        toName: to === userId ? 'You' : debt.name,
        status: debt.status,
        createdAt: debt.createdAt,
        type: debt.type,
        reason: debt.reason
      });
    });

    // 2. Trip Settlements (if included)
    if (includeTrips) {
      const query: any = {
        $or: [
          { 'transactions.from': userId },
          { 'transactions.to': userId },
        ],
      };

      if (tripId) query.tripId = new Types.ObjectId(tripId);

      const settlements = await Settlement.find(query)
        .populate('tripId', 'title baseCurrency')
        .sort({ createdAt: -1 });

      settlements.forEach(settlement => {
        settlement.transactions.forEach((tx: any) => {
          if (tx.from === userId || tx.to === userId) {
            if (status && tx.status !== status) return;

            transactions.push({
              ...tx.toObject(),
              tripId: settlement.tripId,
              settlementId: settlement._id,
              createdAt: settlement.createdAt,
            });
          }
        });
      });
    }

    transactions.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

    return {
      transactions,
      count: transactions.length,
      pending: transactions.filter(t => t.status === 'pending').length,
      confirmed: transactions.filter(t => t.status === 'confirmed').length,
      totalAmount: transactions.reduce((sum, t) => sum + (t.amountBase || t.amount), 0),
    };
  }

  static async getCategories(userId: string, type?: string) {
    const match: any = { userId, isDeleted: false };
    if (type === 'income') {
      match.type = 'income';
    } else if (type === 'expense') {
      match.type = { $in: ['expense', 'trip_expense', 'settlement_paid'] };
    }

    const categories = await Transaction.aggregate([
      { $match: match },
      {
        $group: {
          _id: '$category',
          total: { $sum: '$amount' },
          count: { $sum: 1 },
        },
      },
      { $sort: { total: -1 } },
    ]);

    return categories.map(c => ({
      category: c._id,
      total: c.total,
      count: c.count,
    }));
  }

  static async getTags(userId: string) {
    const tags = await Transaction.aggregate([
      { $match: { userId, isDeleted: false } },
      { $unwind: '$tags' },
      {
        $group: {
          _id: '$tags',
          count: { $sum: 1 },
        },
      },
      { $sort: { count: -1 } },
    ]);

    return tags.map(t => ({
      tag: t._id,
      count: t.count,
    }));
  }

  static async exportTransactions(
    userId: string,
    startDate?: string,
    endDate?: string,
    format: string = 'csv',
    type: string = 'all'
  ) {
    const query: any = {
      userId,
      isDeleted: false,
    };

    if (startDate) query.date = { $gte: new Date(startDate) };
    if (endDate) query.date = { ...query.date, $lte: new Date(endDate) };
    if (type !== 'all') {
      if (type === 'income') {
        query.type = 'income';
      } else {
        query.type = { $in: ['expense', 'trip_expense', 'settlement_paid'] };
      }
    }

    const transactions = await Transaction.find(query)
      .sort({ date: -1 })
      .lean();

    if (format === 'csv') {
      const headers = ['Date', 'Title', 'Type', 'Category', 'Amount', 'Currency', 'Payment Method', 'Notes'];
      const rows = transactions.map(t => [
        new Date(t.date).toLocaleDateString(),
        t.title,
        t.type,
        t.category,
        t.amount,
        t.currency,
        t.paymentMethod,
        t.notes || '',
      ]);

      const csvContent = [
        headers.join(','),
        ...rows.map(row => row.join(',')),
      ].join('\n');

      return csvContent;
    }

    return transactions;
  }

  static async getMonthlyReport(userId: string, month: string) {
    const startDate = new Date(`${month}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

    const [transactions, budget, goals] = await Promise.all([
      Transaction.find({
        userId,
        date: { $gte: startDate, $lte: endDate },
        isDeleted: false,
      }).lean(),
      Budget.findOne({ userId, month }),
      Goal.find({ userId, isCompleted: false }),
    ]);

    const totalIncome = transactions
      .filter(t => t.type === 'income' || t.type === 'settlement_received')
      .reduce((s, t) => s + t.amount, 0);
    const totalExpense = transactions
      .filter(t => ['expense', 'trip_expense', 'settlement_paid'].includes(t.type))
      .reduce((s, t) => s + t.amount, 0);

    const categoryBreakdown: Record<string, number> = {};
    transactions.forEach(t => {
      if (['expense', 'trip_expense'].includes(t.type)) {
        categoryBreakdown[t.category] = (categoryBreakdown[t.category] || 0) + t.amount;
      }
    });

    const totalBudget = budget?.totalBudget ?? 0;
    const totalSpent = budget?.totalSpent ?? 0;

    return {
      month,
      summary: {
        totalIncome,
        totalExpense,
        netSavings: totalIncome - totalExpense,
        budget: totalBudget,
        budgetSpent: totalSpent,
        budgetRemaining: totalBudget - totalSpent,
        budgetUsedPercent: totalBudget > 0
          ? Math.round((totalSpent / totalBudget) * 100)
          : 0,
      },
      categoryBreakdown: Object.entries(categoryBreakdown).map(([category, amount]) => ({
        category,
        amount,
        percent: totalExpense > 0 ? Math.round((amount / totalExpense) * 100) : 0,
      })).sort((a, b) => b.amount - a.amount),
      goals: {
        active: goals.length,
        totalTarget: goals.reduce((s, g) => s + g.targetAmount, 0),
        totalSaved: goals.reduce((s, g) => s + g.savedAmount, 0),
      },
      transactionCount: transactions.length,
      averageDaily: Math.round((totalExpense / new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0).getDate()) * 100) / 100,
    };
  }

  static async getYearlyReport(userId: string, year: string) {
    const monthlyReports = [];
    for (let month = 0; month < 12; month++) {
      const monthStr = `${year}-${String(month + 1).padStart(2, '0')}`;
      const report = await this.getMonthlyReport(userId, monthStr);
      monthlyReports.push(report);
    }

    const totalIncome = monthlyReports.reduce((s, r) => s + r.summary.totalIncome, 0);
    const totalExpense = monthlyReports.reduce((s, r) => s + r.summary.totalExpense, 0);

    const bestMonth = monthlyReports.reduce((best, curr) =>
      curr.summary.netSavings > best.summary.netSavings ? curr : best
    );
    const worstMonth = monthlyReports.reduce((worst, curr) =>
      curr.summary.netSavings < worst.summary.netSavings ? curr : worst
    );

    return {
      year,
      monthlyReports,
      summary: {
        totalIncome,
        totalExpense,
        netSavings: totalIncome - totalExpense,
        averageMonthlyExpense: Math.round(totalExpense / 12 * 100) / 100,
        bestMonth: bestMonth || null,
        worstMonth: worstMonth || null,
      },
    };
  }
}

export default FinanceService;
