import { Schema, model, Document, Types } from 'mongoose';

// ============================================================
// TYPES
// ============================================================

export type TransactionType = 'income' | 'expense' | 'transfer' | 'trip_expense' | 'settlement_paid' | 'settlement_received';
export type RecurringFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';
export type PaymentMethod = 'Cash' | 'Card' | 'UPI' | 'Net Banking' | 'Wallet' | 'Other';

// ============================================================
// TRANSACTION
// ============================================================

export interface ITransaction extends Document {
  userId: string;                    // Firebase UID
  type: TransactionType;
  amount: number;
  currency: string;
  title: string;
  category: string;
  date: Date;
  time?: string;
  paymentMethod: PaymentMethod;
  notes?: string;
  receiptImage?: string;
  tags: string[];
  isRecurring: boolean;
  recurringFrequency?: RecurringFrequency;
  recurringEndDate?: Date;
  // TripSplit linkage
  tripId?: Types.ObjectId;           // Linked trip
  tripName?: string;                 // Denormalized trip name
  expenseId?: Types.ObjectId;        // Linked expense
  settlementId?: Types.ObjectId;     // Linked settlement
  isAutoGenerated: boolean;          // Created automatically from trip expenses
  myShare?: number;                  // User's share of the expense
  totalExpenseAmount?: number;       // Total expense amount (if split)
  splitWith?: string[];              // Who was this split with (display names)
  // Status
  isDeleted: boolean;
  deletedAt?: Date;
  location?: {
    latitude?: number;
    longitude?: number;
    name?: string;
  };
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================
// BUDGET
// ============================================================

export interface ICategoryBudget {
  category: string;
  amount: number;
  spent: number;
  color?: string;
}

export interface IBudget extends Document {
  userId: string;
  month: string;                     // YYYY-MM
  totalBudget: number;
  totalSpent: number;
  categoryBudgets: ICategoryBudget[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================
// BILL
// ============================================================

export interface IBill extends Document {
  userId: string;
  title: string;
  amount: number;
  currency: string;
  dueDate: Date;
  frequency: RecurringFrequency;
  category: string;
  autoPay: boolean;
  isActive: boolean;
  isPaid: boolean;
  paidThisMonth: boolean;
  paidAmount?: number;
  lastPaidDate?: Date;
  nextDueDate?: Date;
  reminderDays: number;              // Days before due date to remind
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================
// GOAL
// ============================================================

export interface IGoal extends Document {
  userId: string;
  title: string;
  description?: string;
  targetAmount: number;
  savedAmount: number;
  currency: string;
  targetDate: Date;
  category: string;
  icon?: string;
  color?: string;
  isCompleted: boolean;
  completedAt?: Date;
  progress: number;
  monthlyContribution?: number;      // Target monthly savings
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================
// DEBT
// ============================================================

export interface IDebt extends Document {
  userId: string;
  type: 'lent' | 'borrowed';
  amount: number;
  currency: string;
  friendUserId?: string;
  name?: string;
  reason: string;
  status: 'pending' | 'settled';
  date: Date;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================
// FINANCIAL SUMMARY (Aggregated View)
// ============================================================

export interface IFinancialSummary {
  userId: string;
  month: string;
  // Income & Expenses
  totalIncome: number;
  totalExpenses: number;
  netSavings: number;
  // Breakdown
  tripExpenses: number;              // From TripSplit
  manualExpenses: number;            // Manually added
  billsPaid: number;
  settlementsPaid: number;
  settlementsReceived: number;
  // Budget
  totalBudget: number;
  budgetRemaining: number;
  budgetUsedPercent: number;
  // Goals
  totalGoalsTarget: number;
  totalGoalsSaved: number;
  goalsProgress: number;
  activeGoals: number;
  completedGoals: number;
  // Stats
  transactionCount: number;
  averageDailyExpense: number;
  topSpendingCategory: string;
  topSpendingCategoryAmount: number;
  // Trends
  comparedToLastMonth: {
    expensesChange: number;          // Percentage
    incomeChange: number;            // Percentage
    savingsChange: number;           // Percentage
  };
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================
// SCHEMAS
// ============================================================

const transactionSchema = new Schema<ITransaction>(
  {
    userId: { type: String, required: true, index: true },
    type: {
      type: String,
      enum: ['income', 'expense', 'transfer', 'trip_expense', 'settlement_paid', 'settlement_received'],
      required: true,
    },
    amount: { type: Number, required: true, min: 0 },
    currency: { type: String, default: 'INR', uppercase: true },
    title: { type: String, required: true, trim: true, maxlength: 200 },
    category: { type: String, required: true },
    date: { type: Date, required: true, default: Date.now },
    time: { type: String },
    paymentMethod: {
      type: String,
      enum: ['Cash', 'Card', 'UPI', 'Net Banking', 'Wallet', 'Other'],
      required: true,
    },
    notes: { type: String, maxlength: 500 },
    receiptImage: { type: String },
    tags: { type: [String], default: [], index: true },
    isRecurring: { type: Boolean, default: false },
    recurringFrequency: { type: String, enum: ['daily', 'weekly', 'monthly', 'yearly'] },
    recurringEndDate: { type: Date },
    // TripSplit linkage
    tripId: { type: Schema.Types.ObjectId, ref: 'Trip' },
    tripName: { type: String },
    expenseId: { type: Schema.Types.ObjectId, ref: 'Expense' },
    settlementId: { type: Schema.Types.ObjectId, ref: 'Settlement' },
    isAutoGenerated: { type: Boolean, default: false },
    myShare: { type: Number },
    totalExpenseAmount: { type: Number },
    splitWith: [{ type: String }],
    // Status
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date },
    location: {
      latitude: { type: Number },
      longitude: { type: Number },
      name: { type: String },
    },
  },
  { timestamps: true, versionKey: false }
);

// Compound indexes for common queries
transactionSchema.index({ userId: 1, date: -1 });
transactionSchema.index({ userId: 1, type: 1, date: -1 });
transactionSchema.index({ userId: 1, category: 1, date: -1 });
transactionSchema.index({ userId: 1, tripId: 1 });
transactionSchema.index({ userId: 1, isDeleted: 1 });

const categoryBudgetSchema = new Schema<ICategoryBudget>(
  {
    category: { type: String, required: true },
    amount: { type: Number, required: true, min: 0 },
    spent: { type: Number, default: 0 },
    color: { type: String },
  },
  { _id: false }
);

const budgetSchema = new Schema<IBudget>(
  {
    userId: { type: String, required: true, index: true },
    month: { type: String, required: true },
    totalBudget: { type: Number, required: true, min: 0 },
    totalSpent: { type: Number, default: 0 },
    categoryBudgets: { type: [categoryBudgetSchema], default: [] },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true, versionKey: false }
);

budgetSchema.index({ userId: 1, month: 1 }, { unique: true });

const billSchema = new Schema<IBill>(
  {
    userId: { type: String, required: true, index: true },
    title: { type: String, required: true, trim: true, maxlength: 200 },
    amount: { type: Number, required: true, min: 0 },
    currency: { type: String, default: 'INR', uppercase: true },
    dueDate: { type: Date, required: true },
    frequency: {
      type: String,
      enum: ['daily', 'weekly', 'monthly', 'yearly'],
      required: true,
    },
    category: { type: String, required: true },
    autoPay: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },
    isPaid: { type: Boolean, default: false },
    paidThisMonth: { type: Boolean, default: false },
    paidAmount: { type: Number },
    lastPaidDate: { type: Date },
    nextDueDate: { type: Date },
    reminderDays: { type: Number, default: 3 },
    notes: { type: String, maxlength: 500 },
  },
  { timestamps: true, versionKey: false }
);

billSchema.index({ userId: 1, dueDate: 1 });
billSchema.index({ userId: 1, isActive: 1 });

const goalSchema = new Schema<IGoal>(
  {
    userId: { type: String, required: true, index: true },
    title: { type: String, required: true, trim: true, maxlength: 200 },
    description: { type: String, maxlength: 500 },
    targetAmount: { type: Number, required: true, min: 0 },
    savedAmount: { type: Number, default: 0, min: 0 },
    currency: { type: String, default: 'INR', uppercase: true },
    targetDate: { type: Date, required: true },
    category: { type: String, required: true },
    icon: { type: String, default: '🎯' },
    color: { type: String },
    isCompleted: { type: Boolean, default: false },
    completedAt: { type: Date },
    progress: { type: Number, default: 0, min: 0, max: 100 },
    monthlyContribution: { type: Number },
  },
  { timestamps: true, versionKey: false }
);

goalSchema.index({ userId: 1, isCompleted: 1 });

// Pre-save hook for goal progress
goalSchema.pre('save', function (next) {
  if (this.targetAmount > 0) {
    this.progress = Math.min(100, Math.round((this.savedAmount / this.targetAmount) * 100));
  }
  if (this.progress >= 100 && !this.isCompleted) {
    this.isCompleted = true;
    this.completedAt = new Date();
  }
  next();
});

const debtSchema = new Schema<IDebt>(
  {
    userId: { type: String, required: true, index: true },
    type: { type: String, enum: ['lent', 'borrowed'], required: true },
    amount: { type: Number, required: true, min: 0 },
    currency: { type: String, default: 'INR', uppercase: true },
    friendUserId: { type: String },
    name: { type: String },
    reason: { type: String, required: true },
    status: { type: String, enum: ['pending', 'settled'], default: 'pending' },
    date: { type: Date, default: Date.now },
  },
  { timestamps: true, versionKey: false }
);

debtSchema.index({ userId: 1, status: 1 });

// ============================================================
// MODELS
// ============================================================

export const Transaction = model<ITransaction>('Transaction', transactionSchema);
export const Budget = model<IBudget>('Budget', budgetSchema);
export const Bill = model<IBill>('Bill', billSchema);
export const Goal = model<IGoal>('Goal', goalSchema);
export const Debt = model<IDebt>('Debt', debtSchema);
