import { Transaction, Budget, Bill, Goal, ITransaction, IGoal, IBill, IBudget } from './finance.model';
import { Expense } from '../expense/expense.model';
import { Trip } from '../trips/trip.model';
import { Settlement } from '../settlement/settlement.model';
import { User } from '../auth/auth.model';
import mongoose, { Types } from 'mongoose';
import { AppError } from '../../shared/errors/AppError';
import { logger } from '../../config/logger';

// ============================================================
// TYPES
// ============================================================

interface DashboardFilters {
  month?: string;
  includeTripExpenses?: boolean;
}

interface TransactionFilters {
  type?: string;
  category?: string;
  month?: string;
  startDate?: string;
  endDate?: string;
  tripId?: string;
  search?: string;
  tags?: string[];
  limit?: number;
  page?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

interface AnalyticsFilters {
  period?: 'week' | 'month' | 'quarter' | 'year' | 'all';
  startDate?: string;
  endDate?: string;
}

// ============================================================
// FINANCE SERVICE
// ============================================================

export class FinanceService {
  
  // ============================================================
  // SYNC: Pull TripSplit expenses into personal finance
  // ============================================================

  /**
   * Sync all trip expenses for a user into their personal finance transactions.
   * This ensures the finance dashboard shows ALL spending, including trip splits.
   */
  static async syncTripExpenses(userId: string): Promise<{ synced: number; skipped: number }> {
    // Fetch all relevant expenses in one query
    const expenses = await Expense.find({
      $or: [
        { paidBy: userId },
        { 'splits.userId': userId },
      ],
      isArchived: false,
    }).lean();

    if (expenses.length === 0) {
      await this.syncSettlementTransactions(userId);
      return { synced: 0, skipped: 0 };
    }

    // ── Batch fetch: all existing synced transactions for these expenses in one query ──
    const allExpenseIds = expenses.map((e: any) => e._id);
    const existingTxns = await Transaction.find({
      userId,
      expenseId: { $in: allExpenseIds },
      isAutoGenerated: true,
    }).lean();

    // Build a Map for O(1) lookup: expenseId → transaction
    const existingMap = new Map<string, any>();
    existingTxns.forEach((t: any) => {
      existingMap.set(String(t.expenseId), t);
    });

    // ── Batch fetch: all distinct trips referenced by these expenses ──
    const tripIds = [...new Set(expenses.map((e: any) => String(e.tripId)).filter(Boolean))];
    const trips = await Trip.find({ _id: { $in: tripIds } }).select('title').lean();
    const tripMap = new Map<string, string>();
    trips.forEach((t: any) => tripMap.set(String(t._id), t.title));

    let synced = 0;
    let skipped = 0;
    const bulkOps: any[] = [];
    const updateOps: Array<() => Promise<void>> = [];

    for (const expense of expenses) {
      const mySplit = expense.splits.find((s: any) => s.userId === userId);
      const paidBack = expense.splits
        .filter((s: any) => s.isPaid && s.userId !== userId)
        .reduce((sum: number, s: any) => sum + s.amountBase, 0);
      const myAmount = expense.paidBy === userId
        ? expense.amountBase - paidBack
        : (mySplit?.amountBase || 0);

      const existing = existingMap.get(String(expense._id));

      if (existing) {
        // Only update if amounts changed
        if (existing.amount !== myAmount || existing.myShare !== (mySplit?.amountBase ?? 0)) {
          updateOps.push(() =>
            Transaction.updateOne(
              { _id: existing._id },
              { $set: { amount: myAmount, myShare: mySplit?.amountBase || 0, totalExpenseAmount: expense.amountBase } }
            ).then(() => void 0)
          );
          synced++;
        } else {
          skipped++;
        }
        continue;
      }

      // New transaction — prepare for bulk insert
      const splitNames = expense.splits
        .filter((s: any) => s.userId !== userId)
        .map((s: any) => s.displayName);

      bulkOps.push({
        insertOne: {
          document: {
            userId,
            type: 'trip_expense' as ITransaction['type'],
            amount: myAmount,
            currency: expense.baseCurrency,
            title: expense.title,
            category: expense.category,
            date: expense.date,
            paymentMethod: 'Other',
            notes: expense.notes,
            receiptImage: expense.receiptImages?.[0],
            tags: expense.tags || [],
            tripId: expense.tripId,
            tripName: tripMap.get(String(expense.tripId)),
            expenseId: expense._id,
            isAutoGenerated: true,
            myShare: mySplit?.amountBase || 0,
            totalExpenseAmount: expense.amountBase,
            splitWith: splitNames,
            location: expense.location,
            isDeleted: false,
          },
        },
      });
      synced++;
    }

    // Execute all writes in parallel
    await Promise.all([
      bulkOps.length > 0 ? Transaction.bulkWrite(bulkOps, { ordered: false }) : Promise.resolve(),
      ...updateOps.map(op => op()),
      this.syncSettlementTransactions(userId),
    ]);

    logger.info(`Trip expenses synced for user ${userId}: ${synced} new/updated, ${skipped} skipped`);
    return { synced, skipped };
  }

  /**
   * Sync settlement payments as finance transactions.
   */
  static async syncSettlementTransactions(userId: string): Promise<void> {
    const settlements = await Settlement.find({
      $or: [
        { 'transactions.from': userId },
        { 'transactions.to': userId },
      ],
    }).lean();

    if (settlements.length === 0) return;

    // Batch fetch all already-synced settlement transactions for this user
    const settlementIds = settlements.map((s: any) => s._id);
    const existingSettlementTxns = await Transaction.find({
      userId,
      settlementId: { $in: settlementIds },
      isAutoGenerated: true,
    }).select('settlementId title').lean();

    // Build a Set of already-synced keys: `${settlementId}:${title}`
    const syncedKeys = new Set<string>();
    existingSettlementTxns.forEach((t: any) => {
      syncedKeys.add(`${String(t.settlementId)}:${t.title}`);
    });

    const toCreate: any[] = [];

    for (const settlement of settlements) {
      for (const txn of (settlement as any).transactions) {
        if (txn.status !== 'confirmed') continue;

        if (txn.from === userId) {
          const title = `Settlement: Paid ${txn.toName}`;
          if (!syncedKeys.has(`${String(settlement._id)}:${title}`)) {
            toCreate.push({
              userId,
              type: 'settlement_paid',
              amount: txn.amountBase,
              currency: txn.baseCurrency,
              title,
              category: 'settlement',
              date: txn.confirmedAt || new Date(),
              paymentMethod: 'UPI',
              notes: `Trip settlement payment to ${txn.toName}`,
              settlementId: settlement._id,
              isAutoGenerated: true,
              isDeleted: false,
            });
          }
        }

        if (txn.to === userId) {
          const title = `Settlement: Received from ${txn.fromName}`;
          if (!syncedKeys.has(`${String(settlement._id)}:${title}`)) {
            toCreate.push({
              userId,
              type: 'settlement_received',
              amount: txn.amountBase,
              currency: txn.baseCurrency,
              title,
              category: 'settlement',
              date: txn.confirmedAt || new Date(),
              paymentMethod: 'UPI',
              notes: `Trip settlement received from ${txn.fromName}`,
              settlementId: settlement._id,
              isAutoGenerated: true,
              isDeleted: false,
            });
          }
        }
      }
    }

    if (toCreate.length > 0) {
      await Transaction.insertMany(toCreate, { ordered: false });
    }
  }

  // ============================================================
  // TRANSACTION CRUD
  // ============================================================

  static async createTransaction(userId: string, data: Partial<ITransaction>) {
    const transaction = new Transaction({
      ...data,
      userId,
      date: data.date || new Date(),
      isAutoGenerated: false,
    });
    await transaction.save();

    // Update budget if expense
    if (data.type === 'expense' && data.category) {
      const month = (data.date || new Date()).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, month, data.category, data.amount || 0);
    }

    logger.info(`Transaction created: ${userId} - ${data.title}`);
    return transaction;
  }

  static async getTransactions(userId: string, filters: TransactionFilters = {}) {
    const query: any = { userId, isDeleted: false };

    if (filters.type) query.type = filters.type;
    if (filters.category) query.category = filters.category;
    if (filters.tripId) query.tripId = new Types.ObjectId(filters.tripId);
    if (filters.tags && filters.tags.length > 0) query.tags = { $in: filters.tags };
    if (filters.search) {
      query.$or = [
        { title: { $regex: filters.search, $options: 'i' } },
        { notes: { $regex: filters.search, $options: 'i' } },
      ];
    }

    if (filters.month) {
      const startDate = new Date(`${filters.month}-01T00:00:00.000Z`);
      const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);
      query.date = { $gte: startDate, $lte: endDate };
    } else if (filters.startDate || filters.endDate) {
      query.date = {};
      if (filters.startDate) query.date.$gte = new Date(filters.startDate);
      if (filters.endDate) query.date.$lte = new Date(filters.endDate);
    }

    const limit = Math.min(filters.limit || 50, 100);
    const page = Math.max(filters.page || 1, 1);
    const skip = (page - 1) * limit;
    const sortField = filters.sortBy || 'date';
    const sortOrder = filters.sortOrder === 'asc' ? 1 : -1;

    const [transactions, total, summary] = await Promise.all([
      Transaction.find(query)
        .sort({ [sortField]: sortOrder, createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .populate('tripId', 'title coverImage')
        .lean(),
      Transaction.countDocuments(query),
      Transaction.aggregate([
        { $match: query },
        {
          $group: {
            _id: null,
            totalExpense: { $sum: { $cond: [{ $in: ['$type', ['expense', 'trip_expense', 'settlement_paid']] }, '$amount', 0] } },
            totalIncome: { $sum: { $cond: [{ $in: ['$type', ['income', 'settlement_received']] }, '$amount', 0] } },
          },
        },
      ]),
    ]);

    return {
      transactions,
      summary: {
        totalExpense: summary[0]?.totalExpense || 0,
        totalIncome: summary[0]?.totalIncome || 0,
        netAmount: (summary[0]?.totalIncome || 0) - (summary[0]?.totalExpense || 0),
      },
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
        hasMore: skip + transactions.length < total,
      },
    };
  }

  static async getTransactionById(userId: string, transactionId: string) {
    const transaction = await Transaction.findOne({
      _id: transactionId,
      userId,
      isDeleted: false,
    }).populate('tripId', 'title coverImage');

    if (!transaction) throw new AppError('Transaction not found', 404);
    return transaction;
  }

  static async updateTransaction(userId: string, transactionId: string, data: Partial<ITransaction>) {
    const transaction = await Transaction.findOne({
      _id: transactionId,
      userId,
      isDeleted: false,
    });

    if (!transaction) throw new AppError('Transaction not found', 404);

    const oldAmount = transaction.amount;
    const oldCategory = transaction.category;
    const oldType = transaction.type;
    const oldDate = transaction.date;

    // Don't allow editing auto-generated transactions (sync from trips instead)
    if (transaction.isAutoGenerated && (data.amount || data.category)) {
      throw new AppError('Trip expenses are auto-managed. Update the expense in the trip instead.', 400);
    }

    Object.assign(transaction, data);
    await transaction.save();

    // Update budget if expense changed
    if (oldType === 'expense' || oldType === 'trip_expense') {
      const oldMonth = new Date(oldDate).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, oldMonth, oldCategory, -oldAmount);
    }

    if ((data.type === 'expense' || transaction.type === 'expense') && transaction.category) {
      const newMonth = new Date(data.date || oldDate).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, newMonth, transaction.category, data.amount || transaction.amount);
    }

    return transaction;
  }

  static async deleteTransaction(userId: string, transactionId: string, permanent: boolean = false) {
    const transaction = await Transaction.findOne({ _id: transactionId, userId });

    if (!transaction) throw new AppError('Transaction not found', 404);

    if (permanent) {
      // Reverse budget
      if ((transaction.type === 'expense' || transaction.type === 'trip_expense') && transaction.category) {
        const month = new Date(transaction.date).toISOString().substring(0, 7);
        await this.updateBudgetSpent(userId, month, transaction.category, -transaction.amount);
      }
      await transaction.deleteOne();
    } else {
      transaction.isDeleted = true;
      transaction.deletedAt = new Date();
      await transaction.save();
    }

    return { success: true, message: 'Transaction deleted successfully' };
  }

  static async restoreTransaction(userId: string, transactionId: string) {
    const transaction = await Transaction.findOne({
      _id: transactionId,
      userId,
      isDeleted: true,
    });

    if (!transaction) throw new AppError('Transaction not found', 404);

    transaction.isDeleted = false;
    transaction.deletedAt = undefined;
    await transaction.save();

    // Restore budget
    if ((transaction.type === 'expense' || transaction.type === 'trip_expense') && transaction.category) {
      const month = new Date(transaction.date).toISOString().substring(0, 7);
      await this.updateBudgetSpent(userId, month, transaction.category, transaction.amount);
    }

    return transaction;
  }

  // ============================================================
  // BUDGET
  // ============================================================

  static async setBudget(
    userId: string,
    month: string,
    totalBudget: number,
    categoryBudgets: { category: string; amount: number; color?: string }[] = []
  ) {
    // Calculate already spent for each category
    const startDate = new Date(`${month}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

    const transactions = await Transaction.find({
      userId,
      type: { $in: ['expense', 'trip_expense'] },
      date: { $gte: startDate, $lte: endDate },
      isDeleted: false,
    });

    const categorySpent: Record<string, number> = {};
    let totalSpent = 0;
    transactions.forEach(t => {
      categorySpent[t.category] = (categorySpent[t.category] || 0) + t.amount;
      totalSpent += t.amount;
    });

    const categoryBudgetsWithSpent = categoryBudgets.map(cb => ({
      category: cb.category,
      amount: cb.amount,
      spent: categorySpent[cb.category] || 0,
      color: cb.color,
    }));

    const budget = await Budget.findOneAndUpdate(
      { userId, month },
      {
        totalBudget,
        totalSpent,
        categoryBudgets: categoryBudgetsWithSpent,
      },
      { upsert: true, new: true }
    );

    return budget;
  }

  static async getBudget(userId: string, month: string, precomputedTotal?: number) {
    let budget = await Budget.findOne({ userId, month });

    // Use precomputed total when provided (avoids redundant aggregate from dashboard)
    const totalSpent = precomputedTotal !== undefined
      ? precomputedTotal
      : await this.getTotalExpenseForMonth(userId, month);

    if (!budget) {
      budget = await Budget.create({
        userId,
        month,
        totalBudget: 0,
        totalSpent,
        categoryBudgets: [],
      });
    } else if (budget.totalSpent !== totalSpent) {
      budget.totalSpent = totalSpent;
      await budget.save();
    }

    return budget;
  }

  static async updateBudgetSpent(userId: string, month: string, category: string, amountDelta: number) {
    if (amountDelta === 0) return;

    const budget = await Budget.findOne({ userId, month });
    if (!budget) return;

    // Update category spent
    const catBudget = budget.categoryBudgets.find(cb => cb.category === category);
    if (catBudget) {
      catBudget.spent = Math.max(0, (catBudget.spent || 0) + amountDelta);
    }

    // Update total spent
    budget.totalSpent = Math.max(0, (budget.totalSpent || 0) + amountDelta);
    await budget.save();
  }

  static async getTotalExpenseForMonth(userId: string, month: string): Promise<number> {
    const startDate = new Date(`${month}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

    const result = await Transaction.aggregate([
      {
        $match: {
          userId,
          type: { $in: ['expense', 'trip_expense', 'settlement_paid'] },
          date: { $gte: startDate, $lte: endDate },
          isDeleted: false,
        },
      },
      { $group: { _id: null, total: { $sum: '$amount' } } },
    ]);

    return result[0]?.total || 0;
  }

  // ============================================================
  // BILLS
  // ============================================================

  static async createBill(userId: string, data: Partial<IBill>) {
    const bill = new Bill({
      ...data,
      userId,
      nextDueDate: data.dueDate,
    });
    await bill.save();
    return bill;
  }

  static async getBills(userId: string, filters: { isActive?: boolean; category?: string; upcoming?: boolean } = {}) {
    const query: any = { userId };
    if (filters.isActive !== undefined) query.isActive = filters.isActive;
    if (filters.category) query.category = filters.category;
    if (filters.upcoming) {
      query.dueDate = { $gte: new Date() };
      query.isPaid = false;
    }

    return Bill.find(query).sort({ dueDate: 1 }).lean();
  }

  static async getBillById(userId: string, billId: string) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);
    return bill;
  }

  static async updateBill(userId: string, billId: string, data: Partial<IBill>) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);

    Object.assign(bill, data);
    await bill.save();
    return bill;
  }

  static async markBillPaid(userId: string, billId: string, paidAmount?: number) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);

    bill.isPaid = true;
    bill.paidThisMonth = true;
    bill.paidAmount = paidAmount || bill.amount;
    bill.lastPaidDate = new Date();

    // Calculate next due date
    const nextDate = new Date(bill.dueDate);
    switch (bill.frequency) {
      case 'monthly': nextDate.setMonth(nextDate.getMonth() + 1); break;
      case 'weekly': nextDate.setDate(nextDate.getDate() + 7); break;
      case 'yearly': nextDate.setFullYear(nextDate.getFullYear() + 1); break;
    }
    bill.dueDate = nextDate;
    bill.nextDueDate = nextDate;
    bill.isPaid = false;
    bill.paidThisMonth = false;

    await bill.save();

    // Optionally create a transaction for this payment
    await this.createTransaction(userId, {
      type: 'expense',
      amount: paidAmount || bill.amount,
      currency: bill.currency,
      title: `Bill: ${bill.title}`,
      category: bill.category,
      date: new Date(),
      paymentMethod: 'UPI',
      notes: `Bill payment - ${bill.title}`,
      isAutoGenerated: true,
    });

    return bill;
  }

  static async deleteBill(userId: string, billId: string) {
    const bill = await Bill.findOne({ _id: billId, userId });
    if (!bill) throw new AppError('Bill not found', 404);
    await bill.deleteOne();
    return { success: true, message: 'Bill deleted' };
  }

  // ============================================================
  // GOALS
  // ============================================================

  static async createGoal(userId: string, data: Partial<IGoal>) {
    const goal = new Goal({ ...data, userId });
    await goal.save();
    return goal;
  }

  static async getGoals(userId: string, filters: { isCompleted?: boolean } = {}) {
    const query: any = { userId };
    if (filters.isCompleted !== undefined) query.isCompleted = filters.isCompleted;
    return Goal.find(query).sort({ targetDate: 1 }).lean();
  }

  static async getGoalById(userId: string, goalId: string) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);
    return goal;
  }

  static async updateGoal(userId: string, goalId: string, data: Partial<IGoal>) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);

    Object.assign(goal, data);
    await goal.save();
    return goal;
  }

  static async contributeToGoal(userId: string, goalId: string, amount: number) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);
    if (goal.isCompleted) throw new AppError('Goal already completed', 400);

    goal.savedAmount += amount;
    await goal.save();

    // Create transaction for this contribution
    await this.createTransaction(userId, {
      type: 'expense',
      amount,
      currency: goal.currency,
      title: `Goal Contribution: ${goal.title}`,
      category: 'savings',
      date: new Date(),
      paymentMethod: 'Other',
      notes: `Contribution to goal: ${goal.title}`,
      isAutoGenerated: true,
    });

    return goal;
  }

  static async deleteGoal(userId: string, goalId: string) {
    const goal = await Goal.findOne({ _id: goalId, userId });
    if (!goal) throw new AppError('Goal not found', 404);
    await goal.deleteOne();
    return { success: true, message: 'Goal deleted' };
  }

  // ============================================================
  // DASHBOARD & ANALYTICS
  // ============================================================

  static async getDashboard(userId: string, month?: string, includeTripExpenses: boolean = true) {
    const targetMonth = month || new Date().toISOString().substring(0, 7);
    const startDate = new Date(`${targetMonth}-01T00:00:00.000Z`);
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);
    const lastMonthStart = new Date(startDate.getFullYear(), startDate.getMonth() - 1, 1);
    const lastMonthEnd = new Date(startDate.getFullYear(), startDate.getMonth(), 0, 23, 59, 59, 999);

    // ── Fire sync in background — do NOT await, respond from existing data ──
    if (includeTripExpenses) {
      this.syncTripExpenses(userId).catch(err =>
        logger.warn('Background sync failed for dashboard', { userId, err: err.message })
      );
    }

    // ── Single $facet aggregate: current month + last month + category breakdown ──
    const [aggregateResult, goals, bills, completedGoalCount] = await Promise.all([
      Transaction.aggregate([
        {
          $match: {
            userId,
            isDeleted: false,
            date: { $gte: lastMonthStart, $lte: endDate },
          },
        },
        {
          $facet: {
            // Current month totals grouped by type
            currentMonth: [
              { $match: { date: { $gte: startDate, $lte: endDate } } },
              {
                $group: {
                  _id: '$type',
                  total: { $sum: '$amount' },
                  count: { $sum: 1 },
                },
              },
            ],
            // Last month totals grouped by type
            lastMonth: [
              { $match: { date: { $gte: lastMonthStart, $lte: lastMonthEnd } } },
              {
                $group: {
                  _id: '$type',
                  total: { $sum: '$amount' },
                },
              },
            ],
            // Category spending for current month
            categorySpending: [
              { $match: { date: { $gte: startDate, $lte: endDate }, type: { $in: ['expense', 'trip_expense'] } } },
              {
                $group: {
                  _id: '$category',
                  spent: { $sum: '$amount' },
                },
              },
            ],
            // Daily spending for current month (for stats)
            dailySpending: [
              { $match: { date: { $gte: startDate, $lte: endDate }, type: { $in: ['expense', 'trip_expense'] } } },
              {
                $group: {
                  _id: { $dateToString: { format: '%Y-%m-%d', date: '$date' } },
                  total: { $sum: '$amount' },
                },
              },
            ],
            // Recent transactions (current month, sorted by date)
            recentTransactions: [
              { $match: { date: { $gte: startDate, $lte: endDate } } },
              { $sort: { date: -1 } },
              { $limit: 10 },
            ],
          },
        },
      ]),
      Goal.find({ userId, isCompleted: false }).sort({ targetDate: 1 }).lean(),
      Bill.find({ userId, isActive: true }).sort({ dueDate: 1 }).lean(),
      Goal.countDocuments({ userId, isCompleted: true }),
    ]);

    // ── Unpack the aggregate results ──
    const facet = aggregateResult[0];

    // Current month: sum by type
    const currentByType: Record<string, number> = {};
    const currentCount: Record<string, number> = {};
    for (const row of facet.currentMonth) {
      currentByType[row._id] = row.total;
      currentCount[row._id] = row.count;
    }

    // Last month: sum by type
    const lastByType: Record<string, number> = {};
    for (const row of facet.lastMonth) {
      lastByType[row._id] = row.total;
    }

    // Derived totals
    const totalIncome = (currentByType['income'] || 0) + (currentByType['settlement_received'] || 0);
    const totalExpense = (currentByType['expense'] || 0) + (currentByType['trip_expense'] || 0);
    const tripExpenses = currentByType['trip_expense'] || 0;
    const manualExpenses = currentByType['expense'] || 0;
    const settlementsPaid = currentByType['settlement_paid'] || 0;
    const settlementsReceived = currentByType['settlement_received'] || 0;

    const lastMonthExpense = (lastByType['expense'] || 0) + (lastByType['trip_expense'] || 0) + (lastByType['settlement_paid'] || 0);
    const lastMonthIncome = (lastByType['income'] || 0) + (lastByType['settlement_received'] || 0);

    const totalTransactionCount = Object.values(currentCount).reduce((s, c) => s + c, 0);

    // ── Category breakdown ──
    const categorySpendingMap: Record<string, number> = {};
    for (const row of facet.categorySpending) {
      categorySpendingMap[row._id] = row.spent;
    }

    // ── Budget: pass precomputed total so getBudget skips duplicate aggregate ──
    const totalExpenseForBudget = totalExpense + settlementsPaid;
    const budget = await this.getBudget(userId, targetMonth, totalExpenseForBudget);
    const totalBudget = budget?.totalBudget || 0;

    // ── Category breakdown with budget comparison ──
    const categoryBreakdown = Object.entries(categorySpendingMap)
      .map(([category, spent]) => {
        const budgetForCategory = budget?.categoryBudgets?.find((cb: any) => cb.category === category);
        return {
          category,
          spent: Math.round(spent * 100) / 100,
          budget: budgetForCategory?.amount || 0,
          budgetRemaining: (budgetForCategory?.amount || 0) - spent,
          percentOfTotal: totalExpense > 0 ? Math.round((spent / totalExpense) * 100) : 0,
          isOverBudget: budgetForCategory ? spent > budgetForCategory.amount : false,
        };
      })
      .sort((a, b) => b.spent - a.spent);

    const topCategory = categoryBreakdown[0] || { category: 'none', spent: 0, percentOfTotal: 0 };

    // Daily average
    const daysInMonth = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0).getDate();
    const daysElapsed = Math.min(new Date().getDate(), daysInMonth);
    const averageDailyExpense = daysElapsed > 0 ? totalExpense / daysElapsed : 0;

    // MoM changes
    const expensesChange = lastMonthExpense > 0
      ? Math.round(((totalExpense - lastMonthExpense) / lastMonthExpense) * 100)
      : 0;
    const incomeChange = lastMonthIncome > 0
      ? Math.round(((totalIncome - lastMonthIncome) / lastMonthIncome) * 100)
      : 0;
    const netCurrent = totalIncome - totalExpense;
    const netLast = lastMonthIncome - lastMonthExpense;
    const savingsChange = netLast !== 0
      ? Math.round(((netCurrent - netLast) / Math.abs(netLast)) * 100)
      : 0;

    // ── Bills ──
    const upcomingBills = bills.filter((b: any) => {
      const daysUntilDue = Math.ceil((new Date(b.dueDate).getTime() - Date.now()) / 86400000);
      return daysUntilDue <= 7 && daysUntilDue >= 0 && !b.paidThisMonth;
    });

    return {
      monthlyOverview: {
        month: targetMonth,
        totalIncome: Math.round(totalIncome * 100) / 100,
        totalExpense: Math.round(totalExpense * 100) / 100,
        netSavings: Math.round((totalIncome - totalExpense) * 100) / 100,
        budget: totalBudget,
        budgetSpent: budget?.totalSpent || 0,
        budgetRemaining: totalBudget - (budget?.totalSpent || 0),
        budgetUsedPercent: totalBudget > 0 ? Math.round(((budget?.totalSpent || 0) / totalBudget) * 100) : 0,
        averageDailyExpense: Math.round(averageDailyExpense * 100) / 100,
        tripExpenses: Math.round(tripExpenses * 100) / 100,
        manualExpenses: Math.round(manualExpenses * 100) / 100,
        settlementsPaid: Math.round(settlementsPaid * 100) / 100,
        settlementsReceived: Math.round(settlementsReceived * 100) / 100,
        comparedToLastMonth: { expensesChange, incomeChange, savingsChange },
      },
      categoryBreakdown,
      topSpendingCategory: {
        category: topCategory.category,
        amount: topCategory.spent,
        percentOfTotal: topCategory.percentOfTotal || 0,
      },
      recentTransactions: facet.recentTransactions,
      goals: {
        active: goals.length,
        completed: completedGoalCount,
        items: goals.slice(0, 5),
        totalTarget: goals.reduce((s: number, g: any) => s + g.targetAmount, 0),
        totalSaved: goals.reduce((s: number, g: any) => s + g.savedAmount, 0),
      },
      bills: {
        total: bills.length,
        upcoming: upcomingBills,
        upcomingCount: upcomingBills.length,
        totalDueThisMonth: bills
          .filter((b: any) => !b.paidThisMonth)
          .reduce((s: number, b: any) => s + b.amount, 0),
      },
      stats: {
        transactionCount: totalTransactionCount,
        daysWithExpenses: facet.dailySpending.length,
      },
    };
  }

  /**
   * Get spending analytics for a period.
   */
  static async getAnalytics(userId: string, filters: AnalyticsFilters = {}) {
    let startDate: Date;
    let endDate: Date = new Date();

    switch (filters.period) {
      case 'week':
        startDate = new Date(Date.now() - 7 * 86400000);
        break;
      case 'month':
        startDate = new Date(Date.now() - 30 * 86400000);
        break;
      case 'quarter':
        startDate = new Date(Date.now() - 90 * 86400000);
        break;
      case 'year':
        startDate = new Date(Date.now() - 365 * 86400000);
        break;
      case 'all':
        startDate = new Date(0);
        break;
      default:
        startDate = filters.startDate ? new Date(filters.startDate) : new Date(Date.now() - 30 * 86400000);
        endDate = filters.endDate ? new Date(filters.endDate) : new Date();
    }

    const transactions = await Transaction.find({
      userId,
      date: { $gte: startDate, $lte: endDate },
      isDeleted: false,
      type: { $in: ['expense', 'trip_expense'] },
    }).sort({ date: 1 }).lean();

    // Daily spending trend
    const dailyTrend: Record<string, number> = {};
    transactions.forEach(t => {
      const key = new Date(t.date).toISOString().split('T')[0];
      dailyTrend[key] = (dailyTrend[key] || 0) + t.amount;
    });

    // Category distribution
    const categoryDistribution: Record<string, number> = {};
    transactions.forEach(t => {
      categoryDistribution[t.category] = (categoryDistribution[t.category] || 0) + t.amount;
    });

    const totalSpent = transactions.reduce((s, t) => s + t.amount, 0);

    // Payment method distribution
    const paymentMethods: Record<string, number> = {};
    transactions.forEach(t => {
      const method = t.paymentMethod || 'Other';
      paymentMethods[method] = (paymentMethods[method] || 0) + t.amount;
    });

    // Trip vs Manual breakdown
    const tripExpenseTotal = transactions
      .filter(t => t.type === 'trip_expense')
      .reduce((s, t) => s + t.amount, 0);
    const manualExpenseTotal = transactions
      .filter(t => t.type === 'expense')
      .reduce((s, t) => s + t.amount, 0);

    // Monthly trend
    const monthlyTrend: Record<string, number> = {};
    transactions.forEach(t => {
      const key = new Date(t.date).toISOString().substring(0, 7);
      monthlyTrend[key] = (monthlyTrend[key] || 0) + t.amount;
    });

    return {
      period: {
        startDate,
        endDate,
        days: Math.ceil((endDate.getTime() - startDate.getTime()) / 86400000),
      },
      overview: {
        totalSpent: Math.round(totalSpent * 100) / 100,
        averagePerTransaction: transactions.length > 0
          ? Math.round((totalSpent / transactions.length) * 100) / 100
          : 0,
        transactionCount: transactions.length,
        averageDaily: Math.round((totalSpent / Math.max(1, Math.ceil((endDate.getTime() - startDate.getTime()) / 86400000))) * 100) / 100,
      },
      dailyTrend: Object.entries(dailyTrend).map(([date, amount]) => ({
        date,
        amount: Math.round(amount * 100) / 100,
      })).sort((a, b) => a.date.localeCompare(b.date)),
      monthlyTrend: Object.entries(monthlyTrend).map(([month, amount]) => ({
        month,
        amount: Math.round(amount * 100) / 100,
      })).sort((a, b) => a.month.localeCompare(b.month)),
      categoryDistribution: Object.entries(categoryDistribution)
        .map(([category, amount]) => ({
          category,
          amount: Math.round(amount * 100) / 100,
          percent: totalSpent > 0 ? Math.round((amount / totalSpent) * 100) : 0,
        }))
        .sort((a, b) => b.amount - a.amount),
      paymentMethods: Object.entries(paymentMethods)
        .map(([method, amount]) => ({
          method,
          amount: Math.round(amount * 100) / 100,
          percent: totalSpent > 0 ? Math.round((amount / totalSpent) * 100) : 0,
        }))
        .sort((a, b) => b.amount - a.amount),
      tripVsManual: {
        tripExpenses: Math.round(tripExpenseTotal * 100) / 100,
        manualExpenses: Math.round(manualExpenseTotal * 100) / 100,
        tripPercent: totalSpent > 0 ? Math.round((tripExpenseTotal / totalSpent) * 100) : 0,
        manualPercent: totalSpent > 0 ? Math.round((manualExpenseTotal / totalSpent) * 100) : 0,
      },
    };
  }
}



// // finance.service.ts
// import { Transaction, Budget, Bill, Goal, ITransaction, IGoal, IBill, IBudget } from './finance.model';
// import mongoose from 'mongoose';
// import { AppError } from '../../shared/errors/AppError';

// interface DashboardFilters {
//   month?: string;
//   type?: string;
//   category?: string;
//   limit?: number;
// }

// interface TransactionFilters {
//   type?: string;
//   category?: string;
//   month?: string;
//   startDate?: string;
//   endDate?: string;
//   limit?: number;
//   page?: number;
// }

// export class FinanceService {
//   // ============================================================
//   // TRANSACTION CRUD
//   // ============================================================

//   static async createTransaction(userId: string, data: Partial<ITransaction>) {
//     const transaction = new Transaction({ 
//       ...data, 
//       userId,
//       date: data.date || new Date(),
//     });
//     await transaction.save();

//     // Update category budget spent
//     if (data.type === 'expense' && data.category) {
//       const month = new Date(data.date || Date.now()).toISOString().substring(0, 7);
//       await this.updateCategoryBudgetSpent(userId, month, data.category, data.amount || 0);
//     }

//     return transaction;
//   }

//   static async getTransactions(userId: string, filters: TransactionFilters = {}) {
//     const query: any = { userId, isDeleted: false };
    
//     if (filters.type) query.type = filters.type;
//     if (filters.category) query.category = filters.category;
    
//     if (filters.month) {
//       const startDate = new Date(`${filters.month}-01T00:00:00Z`);
//       const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);
//       query.date = { $gte: startDate, $lte: endDate };
//     } else if (filters.startDate && filters.endDate) {
//       query.date = {
//         $gte: new Date(filters.startDate),
//         $lte: new Date(filters.endDate)
//       };
//     }

//     const limit = Math.min(filters.limit || 50, 100);
//     const page = Math.max(filters.page || 1, 1);
//     const skip = (page - 1) * limit;

//     const [transactions, total] = await Promise.all([
//       Transaction.find(query)
//         .sort({ date: -1, createdAt: -1 })
//         .skip(skip)
//         .limit(limit)
//         .populate('tripId', 'title coverImage'),
//       Transaction.countDocuments(query)
//     ]);

//     return {
//       transactions,
//       pagination: {
//         page,
//         limit,
//         total,
//         totalPages: Math.ceil(total / limit),
//       }
//     };
//   }

//   static async getTransactionById(userId: string, transactionId: string) {
//     const transaction = await Transaction.findOne({ 
//       _id: transactionId, 
//       userId,
//       isDeleted: false 
//     }).populate('tripId', 'title coverImage');

//     if (!transaction) {
//       throw new AppError('Transaction not found', 404);
//     }

//     return transaction;
//   }

//   static async updateTransaction(userId: string, transactionId: string, data: Partial<ITransaction>) {
//     const transaction = await Transaction.findOne({ 
//       _id: transactionId, 
//       userId,
//       isDeleted: false 
//     });

//     if (!transaction) {
//       throw new AppError('Transaction not found', 404);
//     }

//     // If amount or category changed, update budget
//     const oldAmount = transaction.amount;
//     const oldCategory = transaction.category;
//     const oldType = transaction.type;

//     Object.assign(transaction, data);
//     await transaction.save();

//     // Update category budget if expense changed
//     if (oldType === 'expense') {
//       const month = new Date(transaction.date).toISOString().substring(0, 7);
      
//       // Reverse old
//       await this.updateCategoryBudgetSpent(userId, month, oldCategory, -oldAmount);
      
//       // Apply new
//       if (data.type === 'expense') {
//         const newMonth = new Date(data.date || transaction.date).toISOString().substring(0, 7);
//         const newAmount = data.amount || transaction.amount;
//         const newCategory = data.category || transaction.category;
//         await this.updateCategoryBudgetSpent(userId, newMonth, newCategory, newAmount);
//       }
//     }

//     return transaction;
//   }

//   static async deleteTransaction(userId: string, transactionId: string, permanent: boolean = false) {
//     const transaction = await Transaction.findOne({ 
//       _id: transactionId, 
//       userId 
//     });

//     if (!transaction) {
//       throw new AppError('Transaction not found', 404);
//     }

//     if (permanent) {
//       // If expense, reverse budget
//       if (transaction.type === 'expense') {
//         const month = new Date(transaction.date).toISOString().substring(0, 7);
//         await this.updateCategoryBudgetSpent(userId, month, transaction.category, -transaction.amount);
//       }
//       await transaction.deleteOne();
//     } else {
//       // Soft delete
//       transaction.isDeleted = true;
//       transaction.deletedAt = new Date();
//       await transaction.save();
//     }

//     return { success: true, message: 'Transaction deleted successfully' };
//   }

//   static async restoreTransaction(userId: string, transactionId: string) {
//     const transaction = await Transaction.findOne({ 
//       _id: transactionId, 
//       userId,
//       isDeleted: true 
//     });

//     if (!transaction) {
//       throw new AppError('Transaction not found', 404);
//     }

//     transaction.isDeleted = false;
//     transaction.deletedAt = undefined;
//     await transaction.save();

//     // Restore budget if expense
//     if (transaction.type === 'expense') {
//       const month = new Date(transaction.date).toISOString().substring(0, 7);
//       await this.updateCategoryBudgetSpent(userId, month, transaction.category, transaction.amount);
//     }

//     return transaction;
//   }

//   // ============================================================
//   // BUDGET CRUD
//   // ============================================================

//   static async setBudget(
//     userId: string, 
//     month: string, 
//     totalBudget: number, 
//     categoryBudgets: { category: string; amount: number }[] = []
//   ) {
//     // Calculate spent for each category from transactions
//     const startDate = new Date(`${month}-01T00:00:00Z`);
//     const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

//     const transactions = await Transaction.find({
//       userId,
//       type: 'expense',
//       date: { $gte: startDate, $lte: endDate },
//       isDeleted: false
//     });

//     const categorySpent: Record<string, number> = {};
//     transactions.forEach(t => {
//       categorySpent[t.category] = (categorySpent[t.category] || 0) + t.amount;
//     });

//     const categoryBudgetsWithSpent = categoryBudgets.map(cb => ({
//       ...cb,
//       spent: categorySpent[cb.category] || 0
//     }));

//     const budget = await Budget.findOneAndUpdate(
//       { userId, month },
//       { 
//         totalBudget, 
//         categoryBudgets: categoryBudgetsWithSpent 
//       },
//       { upsert: true, new: true }
//     );

//     return budget;
//   }

//   static async getBudget(userId: string, month: string) {
//     let budget = await Budget.findOne({ userId, month });
    
//     // If no budget found, create default
//     if (!budget) {
//       const totalExpense = await this.getTotalExpenseForMonth(userId, month);
//       budget = await Budget.create({
//         userId,
//         month,
//         totalBudget: 0,
//         categoryBudgets: []
//       });
//     }

//     return budget;
//   }

//   static async updateCategoryBudgetSpent(
//     userId: string, 
//     month: string, 
//     category: string, 
//     amountDelta: number
//   ) {
//     if (amountDelta === 0) return;

//     const budget = await Budget.findOne({ userId, month });
//     if (!budget) return;

//     // Update category budget spent
//     const categoryBudget = budget.categoryBudgets.find(cb => cb.category === category);
//     if (categoryBudget) {
//       categoryBudget.spent = Math.max(0, (categoryBudget.spent || 0) + amountDelta);
//     }

//     await budget.save();
//   }

//   static async getTotalExpenseForMonth(userId: string, month: string) {
//     const startDate = new Date(`${month}-01T00:00:00Z`);
//     const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

//     const result = await Transaction.aggregate([
//       {
//         $match: {
//           userId,
//           type: 'expense',
//           date: { $gte: startDate, $lte: endDate },
//           isDeleted: false
//         }
//       },
//       {
//         $group: {
//           _id: null,
//           total: { $sum: '$amount' }
//         }
//       }
//     ]);

//     return result[0]?.total || 0;
//   }

//   // ============================================================
//   // BILL CRUD
//   // ============================================================

//   static async createBill(userId: string, data: Partial<IBill>) {
//     const bill = new Bill({ ...data, userId });
//     await bill.save();
//     return bill;
//   }

//   static async getBills(userId: string, filters: { isActive?: boolean; category?: string } = {}) {
//     const query: any = { userId };
//     if (filters.isActive !== undefined) query.isActive = filters.isActive;
//     if (filters.category) query.category = filters.category;

//     return Bill.find(query).sort({ dueDate: 1 });
//   }

//   static async getBillById(userId: string, billId: string) {
//     const bill = await Bill.findOne({ _id: billId, userId });
//     if (!bill) {
//       throw new AppError('Bill not found', 404);
//     }
//     return bill;
//   }

//   static async updateBill(userId: string, billId: string, data: Partial<IBill>) {
//     const bill = await Bill.findOne({ _id: billId, userId });
//     if (!bill) {
//       throw new AppError('Bill not found', 404);
//     }

//     Object.assign(bill, data);
//     await bill.save();
//     return bill;
//   }

//   static async deleteBill(userId: string, billId: string) {
//     const bill = await Bill.findOne({ _id: billId, userId });
//     if (!bill) {
//       throw new AppError('Bill not found', 404);
//     }

//     await bill.deleteOne();
//     return { success: true, message: 'Bill deleted successfully' };
//   }

//   // ============================================================
//   // GOAL CRUD
//   // ============================================================

//   static async createGoal(userId: string, data: Partial<IGoal>) {
//     const goal = new Goal({ ...data, userId });
//     await goal.save();
//     return goal;
//   }

//   static async getGoals(userId: string, filters: { isCompleted?: boolean } = {}) {
//     const query: any = { userId };
//     if (filters.isCompleted !== undefined) query.isCompleted = filters.isCompleted;

//     return Goal.find(query).sort({ targetDate: 1 });
//   }

//   static async getGoalById(userId: string, goalId: string) {
//     const goal = await Goal.findOne({ _id: goalId, userId });
//     if (!goal) {
//       throw new AppError('Goal not found', 404);
//     }
//     return goal;
//   }

//   static async updateGoal(userId: string, goalId: string, data: Partial<IGoal>) {
//     const goal = await Goal.findOne({ _id: goalId, userId });
//     if (!goal) {
//       throw new AppError('Goal not found', 404);
//     }

//     Object.assign(goal, data);
//     if (goal.savedAmount >= goal.targetAmount) {
//       goal.isCompleted = true;
//     }
//     await goal.save();
//     return goal;
//   }

//   static async deleteGoal(userId: string, goalId: string) {
//     const goal = await Goal.findOne({ _id: goalId, userId });
//     if (!goal) {
//       throw new AppError('Goal not found', 404);
//     }

//     await goal.deleteOne();
//     return { success: true, message: 'Goal deleted successfully' };
//   }

//   // ============================================================
//   // DASHBOARD
//   // ============================================================

//   static async getDashboard(userId: string, month: string) {
//     const startDate = new Date(`${month}-01T00:00:00Z`);
//     const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

//     // Get all transactions for the month
//     const transactions = await Transaction.find({
//       userId,
//       date: { $gte: startDate, $lte: endDate },
//       isDeleted: false
//     }).sort({ date: -1 });

//     let totalExpense = 0;
//     let totalIncome = 0;
//     const categorySpending: Record<string, { spent: number; budget: number }> = {};

//     transactions.forEach(t => {
//       if (t.type === 'expense') {
//         totalExpense += t.amount;
//         if (!categorySpending[t.category]) {
//           categorySpending[t.category] = { spent: 0, budget: 0 };
//         }
//         categorySpending[t.category].spent += t.amount;
//       } else if (t.type === 'income') {
//         totalIncome += t.amount;
//       }
//     });

//     // Get Budget
//     const budget = await Budget.findOne({ userId, month });
//     const totalBudget = budget?.totalBudget || 0;

//     // Populate category budgets
//     const categoryBudgets = budget?.categoryBudgets || [];
//     const categorySpendingArray = Object.keys(categorySpending).map(cat => ({
//       category: cat,
//       spent: categorySpending[cat].spent,
//       budget: categoryBudgets.find(b => b.category === cat)?.amount || 0,
//     }));

//     // Get goals & bills
//     const [goals, bills] = await Promise.all([
//       Goal.find({ userId, isCompleted: false }).sort({ targetDate: 1 }),
//       Bill.find({ userId, isActive: true }).sort({ dueDate: 1 }),
//     ]);

//     return {
//       monthlyOverview: {
//         totalExpense,
//         totalIncome,
//         savings: totalIncome - totalExpense,
//         budget: totalBudget,
//         budgetUsedPercentage: totalBudget > 0 ? (totalExpense / totalBudget) * 100 : 0,
//       },
//       categorySpending: categorySpendingArray,
//       recentTransactions: transactions.slice(0, 10),
//       goals,
//       bills,
//       // Additional stats
//       stats: {
//         transactionCount: transactions.length,
//         expenseCount: transactions.filter(t => t.type === 'expense').length,
//         incomeCount: transactions.filter(t => t.type === 'income').length,
//         averageDailyExpense: totalExpense / (new Date().getDate() || 1),
//       }
//     };
//   }
// }


// // import { Transaction, Budget, Bill, Goal, ITransaction } from './finance.model';

// // export class FinanceService {
// //   // ============================================================
// //   // TRANSACTIONS
// //   // ============================================================

// //   static async addTransaction(userId: string, data: Partial<ITransaction>) {
// //     const transaction = new Transaction({ ...data, userId });
// //     await transaction.save();

// //     // If it's an expense, update the budget for that month
// //     if (data.type === 'expense') {
// //       const month = new Date(data.date || Date.now()).toISOString().substring(0, 7); // YYYY-MM
// //       const amount = data.amount || 0;
// //       // We don't automatically deduct from total spent here unless we query the budget on read,
// //       // or we can just calculate totalSpent dynamically on the dashboard.
// //     }

// //     return transaction;
// //   }

// //   static async getTransactions(userId: string, filters: any = {}) {
// //     const query: any = { userId };
    
// //     if (filters.type) query.type = filters.type;
// //     if (filters.category) query.category = filters.category;
// //     if (filters.month) {
// //       // filters.month is YYYY-MM
// //       const startDate = new Date(`${filters.month}-01T00:00:00Z`);
// //       const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);
// //       query.date = { $gte: startDate, $lte: endDate };
// //     }

// //     return Transaction.find(query).sort({ date: -1, createdAt: -1 });
// //   }

// //   // ============================================================
// //   // BUDGET
// //   // ============================================================

// //   static async setBudget(userId: string, month: string, totalBudget: number, categoryBudgets: any[]) {
// //     return Budget.findOneAndUpdate(
// //       { userId, month },
// //       { totalBudget, categoryBudgets },
// //       { upsert: true, new: true }
// //     );
// //   }

// //   static async getBudget(userId: string, month: string) {
// //     return Budget.findOne({ userId, month });
// //   }

// //   // ============================================================
// //   // DASHBOARD
// //   // ============================================================

// //   static async getDashboard(userId: string, month: string) {
// //     // 1. Get transactions for the month
// //     const startDate = new Date(`${month}-01T00:00:00Z`);
// //     const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0, 23, 59, 59, 999);

// //     const transactions = await Transaction.find({
// //       userId,
// //       date: { $gte: startDate, $lte: endDate }
// //     }).sort({ date: -1 });

// //     let totalExpense = 0;
// //     let totalIncome = 0;
// //     const categorySpending: Record<string, number> = {};

// //     transactions.forEach(t => {
// //       if (t.type === 'expense') {
// //         totalExpense += t.amount;
// //         categorySpending[t.category] = (categorySpending[t.category] || 0) + t.amount;
// //       } else if (t.type === 'income') {
// //         totalIncome += t.amount;
// //       }
// //     });

// //     // 2. Get Budget
// //     const budget = await Budget.findOne({ userId, month });
    
// //     // 3. Get Goals & Bills (simplified for now)
// //     const goals = await Goal.find({ userId, isCompleted: false });
// //     const bills = await Bill.find({ userId, isActive: true });

// //     return {
// //       monthlyOverview: {
// //         totalExpense,
// //         totalIncome,
// //         savings: totalIncome - totalExpense,
// //         budget: budget?.totalBudget || 0,
// //         budgetUsedPercentage: budget?.totalBudget ? (totalExpense / budget.totalBudget) * 100 : 0,
// //       },
// //       categorySpending: Object.keys(categorySpending).map(cat => ({
// //         category: cat,
// //         spent: categorySpending[cat],
// //         budget: budget?.categoryBudgets.find(b => b.category === cat)?.amount || 0
// //       })),
// //       recentTransactions: transactions.slice(0, 10),
// //       goals,
// //       bills
// //     };
// //   }
// // }
