import { IAchievementDefinition } from './achievement.model';

// ============================================================
// ALL ACHIEVEMENT DEFINITIONS
// ============================================================

export const ACHIEVEMENT_DEFINITIONS: IAchievementDefinition[] = [
    // ── EXPENSE MANAGEMENT ──────────────────────────────────
    {
        achievementId: 'first_expense',
        name: 'Budget Beginner',
        description: 'Add your very first expense',
        icon: '🌱',
        category: 'expense_management',
        tier: 'bronze',
        pointsValue: 10,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'expenses_added', target: 1, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'expense_novice',
        name: 'Expense Apprentice',
        description: 'Add 10 expenses',
        icon: '📝',
        category: 'expense_management',
        tier: 'bronze',
        pointsValue: 25,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'expenses_added', target: 10, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'expense_expert',
        name: 'Expense Expert',
        description: 'Add 50 expenses',
        icon: '📊',
        category: 'expense_management',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'expenses_added', target: 50, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'expense_master',
        name: 'Expense Master',
        description: 'Add 100 expenses',
        icon: '🏆',
        category: 'expense_management',
        tier: 'gold',
        pointsValue: 100,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'expenses_added', target: 100, comparison: 'gte' }],
        repeatable: true,
        cooldownDays: 30,
    },
    {
        achievementId: 'expense_legend',
        name: 'Expense Legend',
        description: 'Add 500 expenses',
        icon: '👑',
        category: 'expense_management',
        tier: 'platinum',
        pointsValue: 250,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'expenses_added', target: 500, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'expense_god',
        name: 'The Accountant',
        description: 'Add 1,000 expenses',
        icon: '🔢',
        category: 'expense_management',
        tier: 'diamond',
        pointsValue: 500,
        isHidden: true,
        criteria: [{ type: 'count', metric: 'expenses_added', target: 1000, comparison: 'gte' }],
        repeatable: false,
    },

    // ── BUDGET MASTERY ──────────────────────────────────────
    {
        achievementId: 'under_budget',
        name: 'Budget Keeper',
        description: 'Complete a trip under budget',
        icon: '💰',
        category: 'budget_mastery',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'ratio', metric: 'budget_compliance', target: 100, comparison: 'lte' }],
        repeatable: true,
        cooldownDays: 7,
    },
    {
        achievementId: 'perfect_budget',
        name: 'Budget Ninja',
        description: 'Complete a trip within 5% of budget',
        icon: '🎯',
        category: 'budget_mastery',
        tier: 'gold',
        pointsValue: 100,
        isHidden: false,
        criteria: [
            { type: 'ratio', metric: 'budget_compliance', target: 95, comparison: 'gte' },
            { type: 'ratio', metric: 'budget_compliance', target: 105, comparison: 'lte' },
        ],
        repeatable: true,
        cooldownDays: 14,
    },
    {
        achievementId: 'big_spender',
        name: 'Big Spender',
        description: 'Total spending exceeds ₹1,00,000',
        icon: '💸',
        category: 'budget_mastery',
        tier: 'gold',
        pointsValue: 75,
        isHidden: false,
        criteria: [{ type: 'sum', metric: 'total_spent', target: 100000, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'frugal_traveler',
        name: 'Frugal Traveler',
        description: 'Complete a trip spending less than ₹500/day',
        icon: '🪙',
        category: 'budget_mastery',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'ratio', metric: 'daily_spend', target: 500, comparison: 'lte' }],
        repeatable: true,
        cooldownDays: 7,
    },

    // ── SPLIT KING ──────────────────────────────────────────
    {
        achievementId: 'equal_splitter',
        name: 'Fair Player',
        description: 'Use equal split 10 times',
        icon: '⚖️',
        category: 'expense_management',
        tier: 'bronze',
        pointsValue: 20,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'equal_splits', target: 10, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'split_master',
        name: 'Split Master',
        description: 'Use all 5 split methods',
        icon: '🎭',
        category: 'expense_management',
        tier: 'gold',
        pointsValue: 100,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'unique_split_methods', target: 5, comparison: 'eq' }],
        repeatable: false,
    },
    {
        achievementId: 'personal_expense_guru',
        name: 'Solo Tracker',
        description: 'Track 20 personal expenses',
        icon: '🚶',
        category: 'expense_management',
        tier: 'silver',
        pointsValue: 40,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'personal_expenses', target: 20, comparison: 'gte' }],
        repeatable: false,
    },

    // ── SOCIAL ACHIEVEMENTS ─────────────────────────────────
    {
        achievementId: 'first_friend',
        name: 'Social Starter',
        description: 'Add your first friend',
        icon: '🤝',
        category: 'social',
        tier: 'bronze',
        pointsValue: 15,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'friends_count', target: 1, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'social_network',
        name: 'Network Builder',
        description: 'Have 10 friends on TripSplit',
        icon: '🌐',
        category: 'social',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'friends_count', target: 10, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'social_butterfly',
        name: 'Social Butterfly',
        description: 'Have 50 friends on TripSplit',
        icon: '🦋',
        category: 'social',
        tier: 'gold',
        pointsValue: 150,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'friends_count', target: 50, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'trip_inviter',
        name: 'Trip Influencer',
        description: 'Invite friends to 5 trips',
        icon: '📨',
        category: 'social',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'trip_invites_sent', target: 5, comparison: 'gte' }],
        repeatable: true,
        cooldownDays: 30,
    },
    {
        achievementId: 'friend_joined_trip',
        name: 'Come Along!',
        description: 'Have a friend join your trip via invite',
        icon: '🎉',
        category: 'social',
        tier: 'bronze',
        pointsValue: 30,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'friends_joined_trips', target: 1, comparison: 'gte' }],
        repeatable: true,
        cooldownDays: 7,
    },

    // ── TRAVEL ACHIEVEMENTS ─────────────────────────────────
    {
        achievementId: 'first_trip',
        name: 'First Adventure',
        description: 'Create your first trip',
        icon: '🗺️',
        category: 'travel',
        tier: 'bronze',
        pointsValue: 20,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'trips_created', target: 1, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'trip_veteran',
        name: 'Seasoned Traveler',
        description: 'Complete 5 trips',
        icon: '✈️',
        category: 'travel',
        tier: 'silver',
        pointsValue: 75,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'trips_completed', target: 5, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'trip_addict',
        name: 'Travel Addict',
        description: 'Complete 20 trips',
        icon: '🌍',
        category: 'travel',
        tier: 'gold',
        pointsValue: 200,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'trips_completed', target: 20, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'globetrotter',
        name: 'Globetrotter',
        description: 'Visit 5 different countries',
        icon: '🌎',
        category: 'travel',
        tier: 'gold',
        pointsValue: 150,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'countries_visited', target: 5, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'world_explorer',
        name: 'World Explorer',
        description: 'Visit 15 different countries',
        icon: '🗺️',
        category: 'travel',
        tier: 'platinum',
        pointsValue: 500,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'countries_visited', target: 15, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'multi_stop_master',
        name: 'Multi-Stop Master',
        description: 'Create a trip with 5+ stops',
        icon: '🚏',
        category: 'travel',
        tier: 'silver',
        pointsValue: 40,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'max_stops_in_trip', target: 5, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'multi_currency',
        name: 'Currency Collector',
        description: 'Use 5+ different currencies across trips',
        icon: '💱',
        category: 'travel',
        tier: 'gold',
        pointsValue: 100,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'currencies_used', target: 5, comparison: 'gte' }],
        repeatable: false,
    },

    // ── SETTLEMENT ACHIEVEMENTS ─────────────────────────────
    {
        achievementId: 'speed_settler',
        name: 'Speed Settler',
        description: 'Settle all debts within 24 hours of trip end',
        icon: '⚡',
        category: 'settlement',
        tier: 'gold',
        pointsValue: 100,
        isHidden: false,
        criteria: [
            { type: 'count', metric: 'quick_settlements', target: 1, comparison: 'gte' },
        ],
        repeatable: true,
        cooldownDays: 14,
    },
    {
        achievementId: 'debt_free',
        name: 'Debt Free',
        description: 'Fully settle 10 trips',
        icon: '🎊',
        category: 'settlement',
        tier: 'silver',
        pointsValue: 75,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'fully_settled_trips', target: 10, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'upi_pro',
        name: 'UPI Pro',
        description: 'Complete 20 UPI payments for settlements',
        icon: '📲',
        category: 'settlement',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'upi_payments_made', target: 20, comparison: 'gte' }],
        repeatable: false,
    },

    // ── STREAK ACHIEVEMENTS ─────────────────────────────────
    {
        achievementId: 'weekly_warrior',
        name: 'Weekly Warrior',
        description: 'Add expenses for 7 consecutive days during a trip',
        icon: '🔥',
        category: 'streak',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'streak', metric: 'daily_expense_streak', target: 7, comparison: 'gte' }],
        repeatable: true,
        cooldownDays: 30,
    },
    {
        achievementId: 'monthly_master',
        name: 'Monthly Master',
        description: 'Add expenses for 30 consecutive days during a trip',
        icon: '📅',
        category: 'streak',
        tier: 'gold',
        pointsValue: 150,
        isHidden: false,
        criteria: [{ type: 'streak', metric: 'daily_expense_streak', target: 30, comparison: 'gte' }],
        repeatable: true,
        cooldownDays: 60,
    },

    // ── SPECIAL ACHIEVEMENTS ────────────────────────────────
    {
        achievementId: 'receipt_collector',
        name: 'Receipt Collector',
        description: 'Upload 50 receipt photos',
        icon: '📸',
        category: 'special',
        tier: 'silver',
        pointsValue: 50,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'receipts_uploaded', target: 50, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'category_master',
        name: 'Category Master',
        description: 'Use all 7 expense categories',
        icon: '🎨',
        category: 'special',
        tier: 'bronze',
        pointsValue: 30,
        isHidden: false,
        criteria: [{ type: 'count', metric: 'unique_categories_used', target: 7, comparison: 'eq' }],
        repeatable: false,
    },
    {
        achievementId: 'night_owl',
        name: 'Night Owl',
        description: 'Add an expense between 2 AM and 4 AM',
        icon: '🦉',
        category: 'special',
        tier: 'bronze',
        pointsValue: 25,
        isHidden: true,
        criteria: [{ type: 'first', metric: 'night_expense', target: 1, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'early_bird',
        name: 'Early Bird',
        description: 'Add an expense before 6 AM',
        icon: '🌅',
        category: 'special',
        tier: 'bronze',
        pointsValue: 25,
        isHidden: true,
        criteria: [{ type: 'first', metric: 'early_expense', target: 1, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'perfect_timing',
        name: 'Perfect Timing',
        description: 'Add an expense at exactly 12:00 PM',
        icon: '🕛',
        category: 'special',
        tier: 'silver',
        pointsValue: 50,
        isHidden: true,
        criteria: [{ type: 'first', metric: 'noon_expense', target: 1, comparison: 'gte' }],
        repeatable: false,
    },
    {
        achievementId: 'generous_payer',
        name: 'Generous Soul',
        description: 'Pay for an expense where you\'re not included in the split',
        icon: '🎁',
        category: 'special',
        tier: 'gold',
        pointsValue: 100,
        isHidden: true,
        criteria: [{ type: 'count', metric: 'generous_payments', target: 1, comparison: 'gte' }],
        repeatable: true,
        cooldownDays: 7,
    },
];

// Helper to get definition by ID
export const getAchievementDefinition = (id: string): IAchievementDefinition | undefined => {
    return ACHIEVEMENT_DEFINITIONS.find(a => a.achievementId === id);
};

// Get definitions by category
export const getAchievementsByCategory = (category: string): IAchievementDefinition[] => {
    return ACHIEVEMENT_DEFINITIONS.filter(a => a.category === category);
};