import { ITransformer } from '../core/interfaces';
import { Types } from 'mongoose';

export class FinanceTransformer implements ITransformer {
  name = 'FinanceTransformer';

  constructor(private modelName: 'Transaction' | 'Budget' | 'Bill' | 'Goal' | 'Debt') {}

  transform(data: any): any {
    switch (this.modelName) {
      case 'Transaction':
        return {
          id: data._id?.toString(),
          userId: data.userId,
          type: data.type,
          amount: data.amount,
          currency: data.currency || 'INR',
          title: data.title,
          category: data.category,
          date: data.date,
          time: data.time || null,
          paymentMethod: data.paymentMethod === 'Net Banking' ? 'Net_Banking' : data.paymentMethod,
          notes: data.notes || null,
          receiptImage: data.receiptImage || null,
          tags: data.tags || [],
          isRecurring: data.isRecurring || false,
          recurringFrequency: data.recurringFrequency || null,
          recurringEndDate: data.recurringEndDate || null,
          tripId: data.tripId?.toString() || null,
          tripName: data.tripName || null,
          expenseId: data.expenseId?.toString() || null,
          settlementId: data.settlementId?.toString() || null,
          isAutoGenerated: data.isAutoGenerated || false,
          myShare: data.myShare || null,
          totalExpenseAmount: data.totalExpenseAmount || null,
          splitWith: data.splitWith || [],
          isDeleted: data.isDeleted || false,
          deletedAt: data.deletedAt || null,
          locationLat: data.location?.latitude || null,
          locationLng: data.location?.longitude || null,
          locationName: data.location?.name || null,
          createdAt: data.createdAt,
          updatedAt: data.updatedAt,
        };

      case 'Budget':
        return {
          id: data._id?.toString(),
          userId: data.userId,
          month: data.month,
          totalBudget: data.totalBudget,
          totalSpent: data.totalSpent,
          isActive: data.isActive,
          createdAt: data.createdAt,
          updatedAt: data.updatedAt,
          // Handle CategoryBudgets creation
          categoryBudgets: {
            create: (data.categoryBudgets || []).map((cb: any) => ({
              category: cb.category,
              amount: cb.amount,
              spent: cb.spent || 0,
              color: cb.color || null,
            }))
          }
        };

      case 'Bill':
        return {
          id: data._id?.toString(),
          userId: data.userId,
          title: data.title,
          amount: data.amount,
          currency: data.currency || 'INR',
          dueDate: data.dueDate,
          frequency: data.frequency,
          category: data.category,
          autoPay: data.autoPay || false,
          isActive: data.isActive !== undefined ? data.isActive : true,
          isPaid: data.isPaid || false,
          paidThisMonth: data.paidThisMonth || false,
          paidAmount: data.paidAmount || null,
          lastPaidDate: data.lastPaidDate || null,
          nextDueDate: data.nextDueDate || null,
          reminderDays: data.reminderDays || 3,
          notes: data.notes || null,
          createdAt: data.createdAt,
          updatedAt: data.updatedAt,
        };

      case 'Goal':
        return {
          id: data._id?.toString(),
          userId: data.userId,
          title: data.title,
          description: data.description || null,
          targetAmount: data.targetAmount,
          savedAmount: data.savedAmount || 0,
          currency: data.currency || 'INR',
          targetDate: data.targetDate,
          category: data.category,
          icon: data.icon || '🎯',
          color: data.color || null,
          isCompleted: data.isCompleted || false,
          completedAt: data.completedAt || null,
          progress: data.progress || 0,
          monthlyContribution: data.monthlyContribution || null,
          createdAt: data.createdAt,
          updatedAt: data.updatedAt,
        };

      case 'Debt':
        return {
          id: data._id?.toString(),
          userId: data.userId,
          type: data.type,
          amount: data.amount,
          currency: data.currency || 'INR',
          friendUserId: data.friendUserId || null,
          name: data.name || null,
          reason: data.reason,
          status: data.status,
          date: data.date,
          createdAt: data.createdAt,
          updatedAt: data.updatedAt,
        };
        
      default:
        throw new Error(`Transformer for ${this.modelName} not implemented`);
    }
  }
}
